/**
 * Mapa curado dos ícones de categoria do Catálogo (categories.icon, E25/E34).
 *
 * Fonte: SELECT DISTINCT icon FROM categories no banco do Catálogo
 * (doufsxqlfjyuvxuezpln) em 2026-09-17 — 70 nomes. Imports nomeados são
 * tree-shakeáveis; este módulo só entra no bundle via import() dinâmico em
 * catalogShared.tsx (chunk async), nunca no grafo inicial.
 *
 * Nome novo no banco que não estiver aqui: chip renderiza sem ícone
 * (fallback previsto no plano) — adicionar o ícone neste mapa.
 * Chaves em kebab-case, como produzido por toKebabCase (catalogShared.tsx);
 * nomes com dígito ganham alias na grafia canônica do lucide ("flower-2").
 */
import {
  AlarmClock, Backpack, Battery, Beer, Briefcase, Calculator, Calendar, Car,
  ChefHat, Circle, CircleDot, Clock, Coffee, Cpu, CreditCard, Crown, Dices,
  Droplets, Dumbbell, FileText, Flame, Flashlight, Flower2, Gamepad2, Gift,
  Glasses, GlassWater, HardDrive, Headphones, Heart, Image, Key, Keyboard,
  Lamp, Laptop, Layers, Leaf, Lock, Luggage, Megaphone, Monitor, Mouse,
  Notebook, Package, PawPrint, Pen, Pencil, Pill, Pin, Printer, Recycle,
  Ruler, Scissors, Shirt, ShoppingBag, Sparkles, Speaker, Sprout, Sun, Tag,
  Thermometer, TreePine, Trophy, Umbrella, Utensils, Wallet, Watch, Wine,
  Wrench, Zap,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'alarm-clock': AlarmClock,
  backpack: Backpack,
  battery: Battery,
  beer: Beer,
  briefcase: Briefcase,
  calculator: Calculator,
  calendar: Calendar,
  car: Car,
  'chef-hat': ChefHat,
  circle: Circle,
  'circle-dot': CircleDot,
  clock: Clock,
  coffee: Coffee,
  cpu: Cpu,
  'credit-card': CreditCard,
  crown: Crown,
  dices: Dices,
  droplets: Droplets,
  dumbbell: Dumbbell,
  'file-text': FileText,
  flame: Flame,
  flashlight: Flashlight,
  flower2: Flower2,
  'flower-2': Flower2,
  gamepad2: Gamepad2,
  'gamepad-2': Gamepad2,
  gift: Gift,
  glasses: Glasses,
  'glass-water': GlassWater,
  'hard-drive': HardDrive,
  headphones: Headphones,
  heart: Heart,
  image: Image,
  key: Key,
  keyboard: Keyboard,
  lamp: Lamp,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  lock: Lock,
  luggage: Luggage,
  megaphone: Megaphone,
  monitor: Monitor,
  mouse: Mouse,
  notebook: Notebook,
  package: Package,
  'paw-print': PawPrint,
  pen: Pen,
  pencil: Pencil,
  pill: Pill,
  pin: Pin,
  printer: Printer,
  recycle: Recycle,
  ruler: Ruler,
  scissors: Scissors,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  speaker: Speaker,
  sprout: Sprout,
  sun: Sun,
  tag: Tag,
  thermometer: Thermometer,
  'tree-pine': TreePine,
  trophy: Trophy,
  umbrella: Umbrella,
  utensils: Utensils,
  wallet: Wallet,
  watch: Watch,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
};
