import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:5173',
    trace: 'on-first-retry',
  },
  // Screenshots de referência: caminho fixo pedido pela etapa 90 do
  // PLANO_CONTATOS_100_ETAPAS_2026-09-29 — `e2e/__screenshots__/contacts-*.png`
  // (o padrão do Playwright jogaria tudo em `<spec>.ts-snapshots/` com sufixo de
  // projeto). `{platform}` fica no nome de propósito: uma baseline gerada em
  // outro SO não pode ser comparada com o render do Linux do `e2e-logado.yml`.
  snapshotPathTemplate: '{testDir}/__screenshots__/{arg}-{platform}{ext}',
  expect: {
    // Tolerância da etapa 90 (0,2%). `animations: disabled` congela CountUp,
    // pills de layoutId e transições antes da foto.
    toHaveScreenshot: { maxDiffPixelRatio: 0.002, animations: 'disabled' },
  },
  projects: [
    {
      // auth.spec.ts exercita a tela de login deslogada (tabs, validação de
      // formulário) e nunca deve depender do projeto "setup" — rodar só este
      // projeto (ex: npx playwright test --project=chromium) precisa continuar
      // funcionando mesmo sem E2E_TEST_EMAIL/E2E_TEST_PASSWORD definidas.
      name: 'chromium',
      testMatch: /auth\.spec\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      // Tema e acessibilidade na tela deslogada: o teste precisa de navegador real (a
      // disputa é entre estilo INLINE no `<html>` e a classe `.high-contrast`) e não de
      // sessão — então roda no job de PR, sem `setup` e sem secrets.
      name: 'chromium-theme',
      testMatch: /theme-alto-contraste\.spec\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      // Login real (e2e/auth.setup.ts), executado só quando o projeto
      // "chromium-authenticated" ou "chromium-e2e-core" roda (via dependencies
      // abaixo) — nunca bloqueia o projeto "chromium" acima.
      name: 'setup',
      testMatch: /auth\.setup\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      // conversation.spec.ts / messaging.spec.ts: specs autenticados do
      // e2e-logado.yml. Projeto dedicado (em vez de rodar via path de arquivo
      // no CLI sob "chromium-authenticated") para que uma única invocação do
      // Playwright resolva "setup" sozinha via dependencies — ver e2e/README.md.
      name: 'chromium-e2e-core',
      testMatch: [/conversation\.spec\.ts/, /messaging\.spec\.ts/],
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // Demais specs assumem uma sessão já logada, produzida pelo projeto
      // "setup" e salva em e2e/.auth/user.json.
      name: 'chromium-authenticated',
      testIgnore: /auth\.spec\.ts|auth\.setup\.ts|conversation\.spec\.ts|messaging\.spec\.ts/,
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // talkx.spec.ts on Chromium — cobertura focada do Talk X usada pelo
      // workflow e2e-talkx-pr.yml (PR), espelhando firefox-talkx/webkit-talkx.
      // Reusa o storageState gerado pelo projeto "setup".
      name: 'chromium-talkx',
      testMatch: /talkx\.spec\.ts/,
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // talkx-visual.spec.ts — régua visual (X004): captura 1672×941, tema
      // escuro, com a sessão falsa + fixture de X003 (mockTalkXVisual). Roda
      // DESLOGADO (sem setup, sem secrets) no e2e-talkx-pr.yml — a sessão é
      // injetada no localStorage pelo próprio spec.
      name: 'chromium-talkx-visual',
      testMatch: /talkx-visual\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1672, height: 941 },
        colorScheme: 'dark',
      },
    },
    {
      // talkx.spec.ts on Firefox — cross-browser coverage of the Talk X module.
      // Reuses the storageState generated by the "setup" project (auth cookies are
      // browser-agnostic; the same user.json works for all engine projects).
      name: 'firefox-talkx',
      testMatch: /talkx\.spec\.ts/,
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Firefox'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // talkx.spec.ts on WebKit (Safari engine) — cross-browser coverage of the
      // Talk X module. Uses the same storageState as the other auth projects.
      name: 'webkit-talkx',
      testMatch: /talkx\.spec\.ts/,
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Safari'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // auth.spec.ts on Firefox — cross-browser login UI coverage.
      // No dependencies, no storageState: runs without E2E_TEST_EMAIL/E2E_TEST_PASSWORD,
      // safe to include in ci.yml (PR checks cannot reference those secrets).
      name: 'firefox-auth',
      testMatch: /auth\.spec\.ts/,
      use: { ...devices['Desktop Firefox'] },
    },
    {
      // auth.spec.ts on WebKit (Safari engine) — cross-browser login UI coverage.
      // No dependencies, no storageState: safe to include in ci.yml.
      name: 'webkit-auth',
      testMatch: /auth\.spec\.ts/,
      use: { ...devices['Desktop Safari'] },
    },
    {
      // conversation.spec.ts / messaging.spec.ts on Firefox — cross-browser
      // coverage of the authenticated inbox. Reuses the storageState from setup.
      name: 'firefox-conversation',
      testMatch: [/conversation\.spec\.ts/, /messaging\.spec\.ts/],
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Firefox'],
        storageState: 'e2e/.auth/user.json',
      },
    },
    {
      // conversation.spec.ts / messaging.spec.ts on WebKit (Safari engine) —
      // cross-browser coverage of the authenticated inbox.
      name: 'webkit-conversation',
      testMatch: [/conversation\.spec\.ts/, /messaging\.spec\.ts/],
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Safari'],
        storageState: 'e2e/.auth/user.json',
      },
    },
  ],
  webServer: {
    // The application development server intentionally defaults to port 8080.
    // E2E owns an isolated port so Playwright's readiness probe and its browser
    // always exercise the same process, including while a developer is running
    // the app locally on the default port.
    command: 'bun run dev -- --host 127.0.0.1 --port 5173 --strictPort',
    url: 'http://localhost:5173',
    reuseExistingServer: !process.env.CI,
  },
});
