"""Persist reviewed findings/ranges; read source bytes only, no product execution."""
from pathlib import Path
import collections, datetime, hashlib, json

BASE = Path(__file__).resolve().parents[2]
SRC = BASE / 'source'
OUT = BASE / 'reports/auth'
HEAD = 'da307ba5626dce892f0b37cb6762463f55d14a96'
manifest = json.loads((BASE / 'source-integrity.json').read_text())
assert manifest['head_sha'] == HEAD and not manifest['mismatches']
pins = {p['path']: p for p in manifest['files']}
supp = json.loads((OUT / 'second-pass.json').read_text())
assert supp['source_head'] == HEAD

def evidence(path, start, end, symbol, observation=''):
    raw = (SRC / path).read_bytes()
    sha = hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).hexdigest()
    assert sha == pins[path]['git_blob_sha'] and len(raw) == pins[path]['bytes'], path
    assert 1 <= start <= end <= len(raw.decode().splitlines()), (path, start, end)
    return dict(path=path, start_line=start, end_line=end, blob_sha=sha,
                symbol=symbol, observation=observation)

def migration(prefix):
    paths = list((SRC / 'supabase/migrations').glob(prefix + '*.sql'))
    assert len(paths) == 1, prefix
    return str(paths[0].relative_to(SRC))

def add(number, title, flow, precondition, failure, evidences, acceptance, limits, comparison=None):
    record = dict(
        id=f'R2-AUTH-{number:03d}', title=title, severity='medium', priority='P2',
        status='CONFIRMED_STATIC', source_head=HEAD, audit_pass='second',
        consumer_flow=flow, precondition=precondition, failure_and_effect=failure,
        evidence=evidences, offline_probes=[], feature_claim_ids=[],
        prior_comparison=dict(kind='new_not_in_previous_104', ids=[], assessment=comparison or
            'Comparados os 104 registros anteriores por assunto, caminho e cadeia de efeito; não foi localizado equivalente material.'),
        acceptance_criteria=acceptance, limitations=limits + [
            'Fonte fixada e contratos estáticos; não houve alteração de dados, execução de SQL vivo nem comprovação de incidente em produção.'])
    supp['new_findings'] = [f for f in supp['new_findings'] if f['id'] != record['id']]
    supp['new_findings'].append(record)

add(27, 'Usuário pode liberar o próprio flag administrativo de download',
    'AdminView Permitir Download → useAdminData salva profiles.can_download; ImagePreview → useDownloadPermission lê o mesmo campo → libera handleDownload.',
    'Usuário authenticated dono de um perfil normal, com os campos comparados pela policy preservados e não nulos, cujo can_download foi desabilitado pelo administrador.',
    'A policy permissiva permite UPDATE do próprio profile. A policy restritiva conserva role/access_level/permissions/is_active, e o trigger vencedor conserva role/access_level/permissions, mas nenhum deles protege can_download. O manifesto mantém grant UPDATE da tabela para authenticated. Um PATCH do próprio can_download=true passa por essas condições sem mudar outro privilégio. Após refetch/reload, o hook passa a permitir o download que a UI dizia depender do administrador.',
    [evidence('src/components/admin/AdminView.tsx',181,191,'controle administrativo Permitir Download'),
     evidence('src/components/admin/useAdminData.ts',146,165,'persistência de can_download'),
     evidence('src/hooks/system/useDownloadPermission.ts',5,24,'leitura do flag como autoridade da UI'),
     evidence('src/components/inbox/ImagePreview.tsx',22,51,'bloqueio/desbloqueio e efeito download'),
     evidence(migration('20260405230710'),16,41,'own UPDATE e campos restritos'),
     evidence(migration('20260830080000'),40,57,'trigger vencedor omite can_download'),
     evidence('supabase/schema-manifest.json',6662,6666,'grant UPDATE profiles authenticated no snapshot')],
    ['Restringir can_download à autoridade administrativa no banco por privilégio de coluna/RPC ou validação equivalente, mantendo o autoatendimento somente dos campos pessoais autorizados.',
     'Em ambiente isolado, own UPDATE de can_download deve ser negado para agente e permitido ao administrador; verificar também a revogação/refetch do gate.',
     'Definir o alcance real da política de download na UI; não apresentar ocultação de botão como garantia de impossibilidade de copiar mídia já legível.'],
    ['Não abre leitura de imagens ou objetos adicionais: ImagePreview já exibe a mídia. O impacto demonstrado é alteração indevida de um flag administrativo e do comportamento oficial de download.',
     'role/access_level/permissions/is_active possuem proteções verificadas. O achado não afirma elevação a administrador ou reativação irrestrita.',
     'Sucessão de policies/trigger e grant corroborada pela área database; comparação aqui usa o snapshot e arquivos exatos, sem PATCH real.'])

add(28, 'Detalhe do contato mostra zero mensagens e inatividade por props nunca fornecidas',
    'ContactsView abre ContactDetailPanel(contact) → defaults messageCount=0/lastMessageAt=undefined → ContactEngagementScore e quadro Atividade.',
    'Qualquer contato com histórico de mensagens ou mensagem recente aberto pelo fluxo de detalhes da página Contatos.',
    'O único consumidor de produção de ContactDetailPanel não passa messageCount nem lastMessageAt. O painel utiliza os defaults para mostrar 0 Mensagens e nenhuma Última msg e calcula score 0/Inativo. A consulta useContactsSearch chega a enriquecer last_message_at na lista, mas o painel não a utiliza. A timeline possui consulta própria e pode mostrar atividade ao lado desse resumo falso. A ausência da prop é apresentada como ausência de atividade, sem estado desconhecido/loading.',
    [evidence('src/components/contacts/ContactsView.tsx',221,227,'montagem omite dados de atividade'),
     evidence('src/components/contacts/ContactDetailPanel.tsx',122,124,'defaults de atividade'),
     evidence('src/components/contacts/ContactDetailPanel.tsx',202,207,'dados enviados ao score'),
     evidence('src/components/contacts/ContactDetailPanel.tsx',306,332,'resumo zero/data ausente e timeline separada'),
     evidence('src/components/contacts/ContactEngagementScore.tsx',21,59,'zero e ausência de recência viram Inativo'),
     evidence('src/hooks/crm/useContactsSearch.ts',140,154,'consulta de última mensagem existente')],
    ['Obter contagem e última mensagem por consulta canônica de atividade do contato e conectar os valores ao painel.',
     'Separar zero confirmado, carregamento, indisponibilidade e dado não solicitado; só calcular engajamento quando os insumos necessários forem conhecidos.',
     'Validar contato com mensagens recentes, sem mensagens e consulta com erro, inclusive coerência entre timeline e resumo.'],
    ['Não afirma perda de mensagens; a falha está na representação e classificação de atividade.',
     'Não duplica as falhas do Dashboard central: este consumidor e cálculo são componentes específicos da página Contatos.'])

add(29, 'Analytics de Contatos rotula agregados da página atual como totais',
    'useContactsSearch busca página de 50 → ContactsView filteredContacts → ContactContentArea modo analytics → ContactAnalyticsDashboard.',
    'Resultado filtrado com mais de uma página; há contatos, empresas, tipos, tags ou datas fora da página carregada.',
    'Todos os agregados de Analytics usam apenas o array da página atual. O cabeçalho apresenta contacts.length como total, e distribuição por tipo, Top Empresas/Tags e crescimento de 14 dias são calculados sobre o mesmo subconjunto sem identificação de amostra/página. Ordenar ou paginar altera os indicadores sem alterar o universo filtrado. A paginação é de substituição, não acumulação. Já useContactsKpi pagina toda a base elegível: essa proteção foi conferida e não é o consumidor desse dashboard.',
    [evidence('src/hooks/crm/useContactsSearch.ts',11,19,'limite 50 e ordenação'),
     evidence('src/hooks/crm/useContactsSearch.ts',89,115,'consulta com offset e página retornada'),
     evidence('src/components/contacts/ContactsView.tsx',199,207,'envio de filteredContacts'),
     evidence('src/components/contacts/ContactContentArea.tsx',125,130,'montagem de Analytics'),
     evidence('src/components/contacts/ContactAnalyticsDashboard.tsx',26,84,'agregação local e rótulo total'),
     evidence('src/hooks/crm/useContactsKpi.ts',81,105,'controle existente: KPIs paginam toda a base')],
    ['Calcular os agregados sobre o universo filtrado no servidor ou carregar explicitamente todas as páginas necessárias.',
     'Se a intenção for analisar somente a página, identificar esse escopo em todos os totais/gráficos e separar o total do universo.',
     'Conferir conjunto com mais de 50 registros: trocar ordenação/página não deve alterar os agregados do mesmo universo.'],
    ['A ordenação/paginação e os filtros da lista são efetivos; o problema é o escopo apresentado nos indicadores.',
     'Não amplia a conclusão para os KPIs superiores, cuja paginação completa está implementada.'],
    'DASH-METRICS-001 e DASH-CONTROLS-001 anteriores abrangem o Dashboard central. Este caminho específico ContactsView→ContactAnalyticsDashboard não aparece nos 104 e tem causa independente: o array paginado da lista alimenta os gráficos.')

add(30, 'Configurações globais de cadastro, grupos, reabertura e chave ElevenLabs não têm consumidor operacional local',
    'SettingsView aba global → GlobalSettingsSection/IntegrationKeysSection → useGlobalSettings grava global_settings; fluxos de cadastro, mensagens e ElevenLabs usam outros contratos.',
    'Administrador altera user_creation, check_msg_is_group, group_tickets_enabled, auto_reopen_hours ou salva uma nova elevenlabs_api_key nessa UI esperando o comportamento descrito.',
    'A busca de todos os consumidores de global_settings encontrou leituras operacionais de outras chaves, mas nenhum uso dessas cinco configurações. Os quatro controles globais gravam tabela e anunciam sucesso sem mudar os caminhos locais indicados. A chave ElevenLabs salva fica como Configurada na UI, enquanto a Edge TTS obtém ELEVENLABS_API_KEY do ambiente e a envia ao provedor; não consulta o valor salvo. A persistência por si só não cumpre o efeito que esses controles anunciam.',
    [evidence('src/components/settings/SettingsView.tsx',173,179,'montagem da aba global'),
     evidence('src/components/settings/GlobalSettingsSection.tsx',14,30,'sucesso após updateSetting'),
     evidence('src/components/settings/GlobalSettingsSection.tsx',47,50,'promessas de cadastro/grupos'),
     evidence('src/components/settings/GlobalSettingsSection.tsx',86,101,'promessa de reabertura por horas'),
     evidence('src/components/settings/IntegrationKeysSection.tsx',19,25,'chave persistida e finalidade prometida'),
     evidence('src/components/settings/IntegrationKeysSection.tsx',42,56,'salvar chave e anunciar sucesso'),
     evidence('src/hooks/system/useGlobalSettings.ts',55,78,'UPDATE/UPSERT somente em global_settings'),
     evidence('supabase/functions/elevenlabs-tts/index.ts',16,35,'credencial efetiva obtida do ambiente')],
    ['Conectar cada configuração a um consumidor operacional obrigatório e documentar sua semântica, ou remover/identificar claramente o controle sem efeito.',
     'Definir uma única autoridade segura para a chave de integração e mostrar o estado da configuração realmente usada.',
     'Provar em ambiente isolado que cada alteração muda o efeito anunciado e que erros de aplicação não geram mensagem de conclusão.'],
    ['VPS, integrações externas e infraestrutura não incluídas na fonte não foram inspecionadas; um consumidor externo permanece não demonstrado, não é declarado inexistente.',
     'Existem outras chaves global_settings efetivamente consumidas: manutenção WhatsApp, múltiplas conexões, transcrição automática e Meta. Não é um achado sobre a tabela inteira.',
     'RLS de leitura permite admin/supervisor e escrita apenas admin; nenhum valor real de credencial foi lido, exportado ou incluído.'])

add(31, 'Resposta de verificação da senha anterior pode substituir o veredito da senha atual',
    'Cadastro/ResetPassword → PasswordStrengthMeter(password) → efeito com debounce → consulta por prefixo de hash → estado isBreached/breachCount.',
    'Usuário altera uma senha A com consulta já iniciada para senha B; as respostas concluem fora de ordem ou a resposta antiga termina durante o debounce da nova.',
    'A limpeza do efeito cancela somente o timer, não a consulta já iniciada. checkBreach fecha sobre a senha de sua renderização e grava o estado compartilhado sem comparar a senha/requisição atual. Assim a resposta negativa de A pode sobrescrever o resultado positivo de B e exibir Senha não encontrada em vazamentos conhecidos para B, ou exibir falso comprometimento no sentido inverso. O início da troca também conserva o resultado anterior até a próxima consulta. O feedback de segurança não está vinculado ao valor que ele descreve.',
    [evidence('src/components/auth/PasswordStrengthMeter.tsx',78,128,'debounce sem cancelamento/identidade de request'),
     evidence('src/components/auth/PasswordStrengthMeter.tsx',200,230,'veredito apresentado para password atual'),
     evidence('src/pages/Auth.tsx',247,248,'consumidor de cadastro'),
     evidence('src/pages/ResetPassword.tsx',166,175,'consumidor de recuperação')],
    ['Associar veredito ao valor/hash e geração da consulta; cancelar ou ignorar respostas obsoletas.',
     'Ao mudar senha, apresentar estado não verificado/loading, sem reutilizar a confirmação da senha anterior.',
     'Provar duas consultas em ordem inversa, alteração para senha curta/vazia e falha de rede; só a resposta do valor atual pode controlar a UI.'],
    ['Não afirma que o Auth implantado aceite senhas comprometidas: a configuração e validação final do servidor não foram medidas.',
     'Nenhuma senha real nem consulta de senha a serviço externo foi utilizada; a falha decorre da ordem possível de callbacks do código.'])

add(32, 'Auditoria não inclui concessões e revogações de roles nos filtros e no contador sensível',
    'INSERT/DELETE user_roles → trigger audit_role_changes grava role_granted/role_revoked com entity_type=user_roles → AuditLogDashboard classifica e filtra.',
    'Há uma concessão ou revogação de role entre os registros de auditoria consultados por um administrador.',
    'O writer vencedor grava role_granted e role_revoked. O contador Ações Sensíveis só reconhece action contendo delete, role_change ou export, portanto essas duas operações de acesso não entram. O filtro de entidade Usuários consulta igualdade com user, e não user_roles, retirando também os registros de concessão/revogação/alteração da lista. A persistência da trilha está implementada; é o consumidor que interpreta outro vocabulário e pode mostrar ausência de mudanças de acesso.',
    [evidence(migration('20260409224329'),51,54,'trigger ativo de user_roles'),
     evidence(migration('20260924125400'),22,72,'writer vencedor de ações e entidade'),
     evidence('src/components/security/AuditLogDashboard.tsx',68,91,'filtros exatos e classificação sensível'),
     evidence('src/components/security/AuditLogDashboard.tsx',130,134,'contador anunciado'),
     evidence('src/components/security/AuditLogDashboard.tsx',185,196,'opção Usuários usa user'),
     evidence('src/components/security/SecurityView.tsx',144,145,'montagem ativa')],
    ['Derivar filtros/categorias de um contrato compartilhado de ações e entidades, incluindo grant, revoke, change e auto-provisionamento conforme política.',
     'Validar end-to-end isolado INSERT/DELETE/UPDATE de role e conferir filtro de Usuários e contador de ações sensíveis.',
     'Distinguir consulta sem resultados de erro de carregamento; informar recorte/paginação quando exibir contagens parciais.'],
    ['Os eventos continuam gravados e podem aparecer no filtro Todas ou em outros consumidores. Não é falha de criação nem apagamento da trilha.',
     'Cadeia do trigger/corpo final foi corroborada pela área database.'])

add(33, 'Página de roles usa embed inexistente e transforma erro de consulta em listas vazias',
    'Rota /admin/roles → RolesPage → useRolesPageState.fetchUsers → user_roles com embed profiles!user_roles_user_id_fkey.',
    'Administrador abre a página sobre o schema descrito pelas migrations e pelo manifesto fixado.',
    'A FK user_roles_user_id_fkey foi criada para auth.users(id); não há FK para public.profiles nesse nome. A consulta exige justamente profiles por essa FK, e os tipos exportados registram Relationships=[] para user_roles. O erro de relação no PostgREST não é tratado: fetchUsers apenas pula setUsers e termina loading. As quatro colunas ficam em zero/Nenhum usuário com esta role, embora roles existam, e a lista de atribuição considera todos os profiles como sem role porque users permaneceu vazio. A página AdminView faz outra consulta e join manual por user_id, portanto não está indisponível por esta mesma causa.',
    [evidence('src/pages/admin/RolesPage.tsx',23,43,'consumidor e gate administrativo'),
     evidence('src/pages/admin/useRolesPageState.ts',29,52,'embed inválido, erro ignorado e efeito nas opções'),
     evidence('src/pages/admin/RolesPage.tsx',77,112,'listas vazias apresentadas como ausência de roles'),
     evidence(migration('20251215025014'),4,11,'FK real aponta auth.users'),
     evidence('supabase/schema-manifest.json',4562,4562,'presença da FK no snapshot'),
     evidence('src/integrations/supabase/types.ts',8838,8858,'Relationships vazio no tipo exportado'),
     evidence('src/components/admin/useAdminData.ts',57,75,'controle existente: join manual em outra página')],
    ['Usar consulta/RPC/view ou relação real autorizada para ligar roles aos perfis pelo user_id, sem inventar relacionamento no select.',
     'Propagar estado de erro com retry; não transformar falha estrutural de consulta em Nenhum usuário.',
     'Validar consulta real em schema isolado com admin/supervisor/agente/especial e usuários com e sem role; conferir a lista e as opções de atribuição.'],
    ['Não se afirma que roles foram removidas, nem que a autorização Auth/RLS deixa de funcionar.',
     'Não foi disparada consulta contra PostgREST implantado; incompatibilidade da relação é estabelecida pela cadeia SQL/snapshot e pela semântica oficial de resource embedding.',
     'Schema cache/configuração externa fora da fonte não foram medidos.'])

add(34, 'Aba Notas trata erros devolvidos pelo serviço como conclusão e descarta o texto antes de salvar',
    'ConversationTabContent aba notes → NotesTab AddInline/PromiseItem → useContactNotes mutations → ContactService.addNote/updateNote/deleteNote → resposta Supabase.',
    'A requisição de adicionar, alterar ou excluir nota devolve error no objeto Supabase: por exemplo, INSERT negado após perda de visibilidade, erro de validação/servidor ou alteração de promessa de outro autor.',
    'ContactService devolve a resposta integral nas três mutations, sem throwOnError nem inspeção de error. useContactNotes retorna essa promessa como mutationFn, também sem conferir error; por isso a promessa resolvida com erro aciona onSuccess. Adicionar/excluir emitem toast de sucesso e atualizar apenas invalida, sem o aviso de falha. Na adição, AddInline chama onSave e limpa value/dueDate imediatamente; NoteCategoryCard fecha o editor antes de aguardar. Assim o operador pode receber Nota adicionada sem persistência e perde o texto que precisaria reenviar. PromiseItem oferece toggle para notas de qualquer autor, embora o botão excluir nesse consumidor compare corretamente author_id.',
    [evidence('src/components/inbox/chat/ConversationTabContent.tsx',111,117,'montagem ativa da aba Notas'),
     evidence('src/components/inbox/tabs/NotesTab.tsx',25,39,'submit descarta rascunho sem aguardar onSave'),
     evidence('src/components/inbox/tabs/NotesTab.tsx',80,111,'fechamento imediato e gate correto de excluir'),
     evidence('src/components/inbox/tabs/NotesTab.tsx',155,168,'checkbox sem gate de autoria'),
     evidence('src/hooks/crm/useContactNotes.ts',54,107,'mutationFn devolve resultado sem verificar error'),
     evidence('src/hooks/crm/useContactNotes.ts',109,123,'mutateAsync exposto aos consumidores'),
     evidence('src/services/contact.service.ts',126,154,'resposta Supabase não convertida em exceção'),
     evidence(migration('20260909200000'),154,180,'SELECT visível e UPDATE somente pelo autor'),
     evidence('src/components/email/EmailContactPanel.tsx',294,307,'consumidor de email aguarda promessa mas error não provoca catch')],
    ['Converter erros de dados em rejeição explícita no serviço ou no mutationFn e confirmar a linha afetada antes de acionar onSuccess.',
     'Aguardar a mutation no editor, manter o texto em caso de falha e desabilitar envios duplicados enquanto pendente.',
     'Exibir capacidades coerentes para alterar promessas e excluir notas; testar retorno {data:null,error}, zero linhas e sucesso com linha confirmada.',
     'Conferir que erro de persistência gera aviso de erro, mantém editor/rascunho e não emite Nota adicionada ou Nota removida.'],
    ['É outro consumidor/contrato de serviço que AUTH026: ContactNotes da página Contatos confere error, mas não count; aqui o hook ignora error no objeto resolvido.',
     'Exceções JavaScript realmente lançadas, como perfil ausente, entram no onError existente. A falha se refere ao contrato normal de retorno de erro do cliente Supabase.',
     'EmailContactPanel também usa o hook e limpa o mesmo texto após await. Ele protege texto novo digitado durante a requisição, mas não percebe o error engolido; essa proteção foi preservada na análise.',
     'Nenhuma nota real foi criada, alterada ou removida. A garantia de RLS não é contornada; a falha é de feedback e preservação do trabalho.'])

add(35, 'Status WhatsApp converte indisponibilidade em ausência de status e apresenta Offline sem medição',
    'ContactDetails → ContactAccordionSections Status WhatsApp → useWhatsAppStatus → find-status-messages/send-chat-presence → WhatsAppStatusSection.',
    'Operador abre a seção para contato com uma instância resolvida; modo Evolution GO ou resposta de erro/indisponibilidade na consulta de status.',
    'O backend GO devolve explicitamente success:false/notSupported:true. extractStatusRecords aceita somente array ou messages.records, e fetchData não lê error/notSupported: o objeto vira lista vazia. A UI passa a dizer Nenhum status disponível e explica expiração em24h, sem revelar a indisponibilidade. Em toda conclusão normal, mesmo com dados, o hook fixa isOnline:false e lastSeen:null; a segunda chamada envia a própria presença paused, não consulta a presença do contato. Portanto Offline é um valor inventado, não um estado observado.',
    [evidence('src/components/inbox/contact-details/ContactAccordionSections.tsx',70,72,'montagem ativa da seção'),
     evidence('src/hooks/integrations/useWhatsAppStatus.ts',106,118,'objetos não reconhecidos viram array vazio'),
     evidence('src/hooks/integrations/useWhatsAppStatus.ts',191,219,'actions e resultado fulfilled sem inspeção de error'),
     evidence('src/hooks/integrations/useWhatsAppStatus.ts',251,260,'lista e presença fixa'),
     evidence('src/components/inbox/contact-details/WhatsAppStatusSection.tsx',67,85,'ausência e Offline exibidos como fatos'),
     evidence('supabase/functions/evolution-api/index.ts',727,733,'gate GO explícito e retorno do ramo v2'),
     evidence('supabase/functions/evolution-api/index.ts',845,845,'action envia presença própria'),
     evidence('supabase/functions/_shared/evolution-sync-actions.ts',93,100,'resposta notSupported explícita')],
    ['Propagar indisponibilidade/notSupported e erros HTTP/provedor para um estado visual diferente de vazio confirmado.',
     'Mostrar presença desconhecida/indisponível quando não há fonte real; só afirmar Online/Offline/lastSeen a partir de medição válida.',
     'Não executar envio de presença como se fosse leitura; manter a decisão de stories desabilitados claramente identificada, sem reabrir sua ativação por inferência.',
     'Validar resposta GO notSupported, erro no objeto do SDK, lista vazia confirmada e lista real, sem rede de produção.'],
    ['Não afirma que stories devam ser habilitados: GO_GAPS e StoryViewer documentam desativação/ausência de suporte. O achado é a representação enganosa dessa capacidade.',
     'Correlação por nome/sufixo de telefone no ramo com dados também foi lida, mas não se contou vazamento ou associação real indevida sem cenário/retorno externo demonstrado.',
     'Não houve consulta de status real nem envio de presença; confirmação do action backend foi corroborada pela área providers.'])

add(36, 'Sala de Crise calcula alertas operacionais com mensagens respondidas e contas habilitadas',
    'AdminView aba crisis → CrisisRoom.loadMetrics → quatro contagens Supabase → severidades/queueRatio → MODO CRISE ATIVO ou Operação normal.',
    'Há mais de30 mensagens recebidas na última hora, mesmo já respondidas, ou contas habilitadas que não representam agentes online; a sala é aberta pelo staff.',
    'Msgs sem resposta conta todas as mensagens sender=contact da última hora, sem verificar resposta ou estado da conversa. Esse volume é dividido por profiles.is_active e rotulado conv/agente, embora numerador seja mensagens e denominador contas habilitadas. O mesmo denominador aparece como agentes online. Mais de30 mensagens recebidas já respondidas basta para acionar crise. SLA é contado sem janela/estado e erros de consulta viram zero. O monitor anunciado em tempo real só carrega na montagem ou no botão, sem assinatura/polling, portanto mudanças posteriores também ficam invisíveis até atualização manual.',
    [evidence('src/components/admin/AdminView.tsx',278,284,'montagem da aba crisis'),
     evidence('src/components/admin/CrisisRoom.tsx',23,43,'queries e transformação de unidades'),
     evidence('src/components/admin/CrisisRoom.tsx',45,83,'rótulos, thresholds e decisão de crise'),
     evidence('src/components/admin/CrisisRoom.tsx',85,108,'carregamento inicial e promessa de tempo real'),
     evidence('src/components/admin/CrisisRoom.tsx',158,162,'única atualização adicional manual')],
    ['Definir e implementar métricas canônicas de pendência/resposta, conversas atribuídas e presença de agentes, com unidades coerentes.',
     'Definir a janela e estado do SLA usado na crise e separar erro/indisponibilidade de zero confirmado.',
     'Conectar atualização operacional real ou identificar claramente o snapshot e a hora da última consulta.',
     'Conferir fixture com mensagens todas respondidas, contas habilitadas offline, SLA histórico e falha de consulta; nenhum desses proxies deve criar conclusão gerencial sem fundamento.'],
    ['Não é o Dashboard principal coberto por DASH-METRICS-001/DASH-REALTIME-001; CrisisRoom possui suas próprias queries e decisão de severidade, sem referências nos104.',
     'Nenhuma operação de mitigação é disparada pelo modo crise: o efeito comprovado é alerta/diagnóstico gerencial incorreto.',
     'Não se mediu operação, presença ou incidentes reais.'])

add(37, 'Treinamento apresenta e persiste avaliação de desempenho baseada apenas em sorteio',
    'AdminView aba training → TrainingMode.startScenario/sendResponse → finalScore aleatório → feedback sobre empatia/resolução → training_sessions e histórico.',
    'Usuário conclui as respostas do cenário de treinamento com qualquer conteúdo não vazio.',
    'A nota usa exclusivamente secureRandomFloat, produzindo inteiro entre60 e100, sem avaliar as mensagens do agente. O feedback Excelente/boa empatia e resolução ou Bom/mais proativo depende só dessa nota. Ela é gravada como score/status completed e apresentada no resultado e histórico sem identificar que a avaliação é aleatória. O texto Simulador de atendimento e os roteiros fixos explicam a conversa simulada, mas não tornam um juízo de desempenho por sorteio uma medição. A resposta que exigiria melhorar nunca é alcançada pela faixa atual.',
    [evidence('src/components/admin/AdminView.tsx',280,282,'montagem do treinamento'),
     evidence('src/components/admin/TrainingMode.tsx',108,145,'resposta, sorteio, feedback e persistência'),
     evidence('src/lib/secureRandom.ts',14,17,'fonte uniforme independente do conteúdo'),
     evidence('src/components/admin/TrainingMode.tsx',181,197,'notas no histórico de sessões'),
     evidence('src/components/admin/TrainingMode.tsx',235,245,'nota e juízo apresentados ao usuário')],
    ['Identificar claramente notas/dados de demonstração e evitar persistir feedback aleatório como avaliação de desempenho.',
     'Se a intenção é avaliar, definir critérios verificáveis ligados às respostas e revisão humana adequada; se não, remover os juízos avaliativos e registrar apenas conclusão do exercício.',
     'Conferir respostas diferentes e repetições da mesma resposta: a saída deve respeitar o contrato de simulação/avaliação comunicado ao usuário.',
     'Tratar falhas de gravação e manter estado consistente antes de declarar sessão concluída.'],
    ['Não se afirma que o resultado seja usado para promoção, punição ou avaliação definitiva de empregados; nenhum consumidor com esse efeito foi demonstrado.',
     'Roteiros fixos de simulação são compatíveis com treinamento e não são defeito por si só. O achado se limita à nota/feedback sem fundamento e sua apresentação/persistência.',
     'Nenhuma sessão de treinamento real foi criada nem pontuação alterada.'])

add(38, 'Mapa conta contatos com coordenadas também como localização apenas aproximada',
    'ContactContentArea modo map → ContactMapView agrupa todos por DDD e extrai preciseContacts → ContactRegionMap desenha ambos e publica duas contagens.',
    'Existe ao menos um contato carregado com latitude/longitude numéricas e telefone cujo DDD corresponde a uma região plotada. O mapa carrega normalmente.',
    'O conjunto regions inclui todos os contatos, inclusive aqueles enviados em preciseContacts. ContactRegionMap soma regions para Aproximado pelo DDD e desenha uma bolha por região; em seguida desenha o pino confirmado para o mesmo contato e conta-o de novo em Endereço confirmado. Um único contato com coordenada e DDD conhecido resulta em1 confirmado e1 aproximado, embora haja1 contato mapeado. Pode aparecer em dois locais quando o endereço e o centro do DDD divergem. A legenda promete distinguir quantos contatos estão só por aproximação, mas as populações se sobrepõem.',
    [evidence('src/components/contacts/ContactContentArea.tsx',125,130,'montagem ativa do mapa'),
     evidence('src/components/contacts/ContactMapView.tsx',43,60,'agrupamento inclui todos e extração independente de coordenadas'),
     evidence('src/components/contacts/ContactMapView.tsx',65,82,'total de contatos e dois conjuntos passados ao mapa'),
     evidence('src/components/contacts/ContactRegionMap.tsx',59,65,'contagem aproximada sem exclusão dos precisos'),
     evidence('src/components/contacts/ContactRegionMap.tsx',146,180,'duas séries de marcadores'),
     evidence('src/components/contacts/ContactRegionMap.tsx',218,234,'legenda com contagens de confirmação e aproximação')],
    ['Definir conjuntos exclusivos para os pinos precisos e as bolhas de contatos sem coordenada; calcular a legenda sobre os conjuntos efetivamente plotados.',
     'Manter o agrupamento comercial por DDD nos cartões se desejado, mas separar essa classificação do mapa de localização física e dos seus totais.',
     'Conferir um contato preciso, um apenas aproximado e outro de região não plotável: nenhum contato deve inflar a contagem de localizações por aparecer nos dois conjuntos.'],
    ['Não se reabre a decisão de usar DDD como aproximação quando falta coordenada. A falha é a sobreposição do conjunto de aproximação com os endereços já coordenados.',
     'Não depende de coordenadas de produção, nem afirma que o endereço de um cliente real esteja incorreto. Trata-se do contrato do mapa para dados válidos.',
     'Os dados continuam sujeitos ao recorte da lista carregada; AUTH029 trata separadamente do escopo de Analytics.'])

add(39, 'Recálculo atrasado grava coordenadas do endereço anterior e apaga o aviso de desatualização',
    'ContactDialogs edição → ContactForm campos de endereço/Recalcular → getMapboxToken/searchPlaces → onChange funcional → useContactsCRUD.handleEditContact → contacts UPDATE.',
    'No mesmo formulário e contato, há coordenada anterior; o operador altera o endereço paraB e aciona Recalcular. Antes da resposta, altera um campo paraC e depois salva após a resposta deB.',
    'recalcularCoordenada captura o endereço alvo e aguarda duas operações, sem versão/cancelamento nem comparação com os valores atuais. Os campos continuam editáveis. A edição paraC marca a coordenada como possivelmente velha, mas a resposta deB escreve latitude/longitude no estado atual por onChange e limpa incondicionalmente o aviso. O salvamento posterior envia o endereçoC junto das coordenadasB. O botão Recalcular evita duas buscas simultâneas, mas não protege a correlação da resposta com o endereço vigente.',
    [evidence('src/components/contacts/ContactDialogs.tsx',115,129,'formulário e handlers ativos de edição'),
     evidence('src/components/contacts/ContactForm.tsx',117,123,'aviso quando endereço muda com coordenada existente'),
     evidence('src/components/contacts/ContactForm.tsx',145,172,'alvo capturado, await e commit sem comparação'),
     evidence('src/components/contacts/ContactForm.tsx',326,365,'input de endereço permanece editável'),
     evidence('src/components/contacts/ContactForm.tsx',393,435,'outros campos editáveis e bloqueio apenas do botão'),
     evidence('src/components/contacts/useContactsCRUD.ts',300,306,'onChange aplica valores ao estado mais recente'),
     evidence('src/components/contacts/useContactsCRUD.ts',187,219,'endereço e coordenadas atuais compõem o UPDATE')],
    ['Vincular a resposta à assinatura/versão do endereço consultado e descartar conclusão que perdeu essa correspondência.',
     'Cancelar ou invalidar a consulta ao editar novamente, e só remover o aviso após confirmar que a coordenada pertence ao endereço vigente.',
     'Conferir B→busca pendente→C→respostaB→salvar no mesmo contato; coordenadaB não deve ser apresentada ou gravada como correspondente aC.',
     'Preservar a decisão de não apagar automaticamente coordenadas antigas: a correção deve tratar a resposta obsoleta, não remover dados sem ação autorizada.'],
    ['O cenário não depende de alternar contatos nem de remontagem do componente; React.memo não bloqueia a edição, pois os valores mudam.',
     'Se o operador não muda o endereço enquanto a consulta está em voo, essa corrida não ocorre. Nenhum endereço real foi geocodificado nem salvo.'])

add(40, 'Janela relativa do painel de uso de IA fica presa à hora de abertura',
    'ViewRouter ai-usage → AIUsageDashboard Última1h/Atualizar → useAIUsageDashboard memo since → polls/refetch de resumo e logs → totais e histórico.',
    'O painel permanece montado com o mesmo filtro por algum tempo, há logs que deixam de pertencer à janela relativa e ocorre polling de30s ou atualização manual.',
    'since é calculado com Date apenas na montagem ou troca de timeFilter. As consultas periódicas e o botão Atualizar continuam usando esse limite inferior antigo. ai_usage_summary resolve p_until=null para now; a lista usa somente created_at>=since. Logo a janela cresce: selecionada Última1h às12h, a consulta feita às13h ainda inclui registros desde11h, cobrindo duas horas sob o mesmo rótulo. Trocar filtro/remontar recalcula o início, mas o uso contínuo do painel altera o significado dos totais, taxas e gráficos.',
    [evidence('src/pages/ViewRouter.tsx',92,96,'view ai-usage registrada'),
     evidence('src/pages/lazyViews.ts',55,55,'componente importado pela view'),
     evidence('src/components/admin/AIUsageDashboard.tsx',13,38,'consumidor, filtros relativos e atualização manual'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',107,115,'cálculo relativo ao relógio'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',147,175,'since memoizado e polling do resumo'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',198,214,'lista paginada com o mesmo limite antigo'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',287,303,'refetch sem renovar since'),
     evidence(migration('20261003072707'),35,59,'RPC amplia fim até now preservando p_since')],
    ['Calcular limites coerentes para cada ciclo de atualização e compartilhá-los entre resumo, custos e paginação; renovar a janela conforme o filtro relativo anunciado.',
     'Se a intenção for um intervalo fixo, exibir início/fim absolutos e manter ambos estáveis, sem rótulo de últimas horas.',
     'Usar relógio controlado em ambiente isolado: após avançar uma hora e refazer Última1h, excluir registros mais antigos que uma hora e conferir limites equivalentes nos consumidores.'],
    ['As agregações no servidor e a paginação real da lista existem; este achado não reabre o antigo limite de1000 linhas nem afirma que o resumo some apenas a página.',
     'O custo possui contrato próprio com p_until; sua resposta não foi usada para provar crescimento da janela neste registro.',
     'Nenhuma métrica real ou valor faturado foi consultado.'],
    'IA-QUOTA-001 trata ação/tentativa/contabilização, e os antigos achados DASH tratam outro painel. Não foi localizado nos104 o timestamp memoizado deste hook.')

add(41, 'Consulta de custo de IA passa fim nulo e elimina todas as chamadas da janela',
    'AIUsageDashboard → useAIUsageDashboard consulta de custos → ai_usage_cost_summary(p_since,p_until:null) → janela SQL vazia → custoTexto → nenhuma chamada com tarifa aplicável.',
    'Usuário com acesso ao painel e à RPC; existem logs visíveis no período com quantidade medida e tarifa válida para o modelo. A migração versionada está aplicada.',
    'O cliente envia p_until:null explicitamente em todas as consultas. A função de custo exige created_at<p_until e não converte null em now. A comparação com null não é verdadeira para nenhuma linha, portanto janela/com_tarifa/medido ficam vazios, chamadas=0 e custo_medido=null independentemente das tarifas existentes. A UI interpreta isso como nenhuma chamada com tarifa aplicável. ai_usage_summary possui COALESCE para now, mas a função de custo é um contrato separado e não herda esse comportamento. O bloco de uso pode mostrar chamadas ao lado de uma ausência de custo fabricada pelo parâmetro.',
    [evidence('src/components/admin/AIUsageDashboard.tsx',13,19,'consumo do hook e custoTexto'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',181,196,'RPC de custo recebe p_until null'),
     evidence(migration('20261003102707'),26,46,'definição única e predicado com limite nulo'),
     evidence(migration('20261003102707'),80,135,'agregação vazia produz zero chamadas e custo nulo'),
     evidence('src/hooks/analytics/useAIUsageDashboard.ts',271,284,'formatação preserva custo nulo e ausência de tarifa zero'),
     evidence('src/components/admin/AIUsageDashboard.tsx',122,134,'causa falsa exibida no painel'),
     evidence(migration('20261003072707'),47,59,'controle positivo: resumo de uso resolve fim nulo')],
    ['Definir o contrato de limite final e usar a mesma janela válida nas duas RPCs; converter null explicitamente ou enviar fim não nulo pelo consumidor.',
     'Verificar em ambiente isolado uma chamada tarifada, uma sem tarifa, moedas diferentes e janela vazia real, com o mesmo payload usado pela UI.',
     'Não apresentar ausência de tarifa quando a consulta perdeu todas as linhas por parâmetro inválido; expor validação/erro de contrato quando necessário.',
     'Preservar o tratamento existente de moedas diferentes, vigência de tarifa, RLS e ausência real de medição.'],
    ['Sucessão da função conferida por busca da cadeia e corroborada pelo agente database: única criação no arquivo20261003102707. Não houve execução em banco vivo.',
     'Não afirma custo faturado incorreto ou cobrança indevida; o efeito demonstrado é a falha de medição/apresentação no relatório local.',
     'Comparação SQL com NULL documentada na fonte primária PostgreSQL. O problema é independente da janela que cresce em AUTH040.'],
    'Nenhum dos104 achados anteriores menciona ai_usage_cost_summary ou o parâmetro final nulo. IA-QUOTA-001 trata quota por ação/tentativa, não esta consulta de tarifa IA-055.')

add(42, 'Página Conquistas apresenta progresso simulado como pertencente ao usuário',
    'ViewRouter achievements(userId) → AchievementsSystem → timer de800ms carrega MOCK_ACHIEVEMENTS → níveis/progresso/data → AchievementDetailDialog Reivindicar Recompensa.',
    'Usuário abre a view Conquistas, inclusive conta nova sem mensagens/conquistas. O componente termina o timer local de carregamento.',
    'O componente ignora userId para obter dados: sempre carrega os mesmos oito mocks com três conquistas desbloqueadas,400 XP e progressos fixos como756 conversas resolvidas. Datas são sintetizadas a partir de Date.now. A interface não identifica demonstração. Reivindicar a conquista nova emite celebração/toast de XP e muda apenas isNew localmente; não grava recompensa nem altera saldo. Reabrir remonta os mesmos dados e a recompensa pode aparecer nova de novo. Existe outro painel que consulta agent_stats/agent_achievements, mas a view roteada não o utiliza.',
    [evidence('src/pages/ViewRouter.tsx',109,113,'view achievements montada com userId'),
     evidence('src/components/gamification/AchievementsSystem.tsx',45,81,'dados fixos, carregamento sintético e claim local'),
     evidence('src/components/gamification/AchievementsSystem.tsx',130,187,'nível, XP e progresso apresentados sem rótulo de demonstração'),
     evidence('src/components/gamification/AchievementDetailDialog.tsx',61,79,'recompensa e botão reivindicar'),
     evidence('src/hooks/gamification/useAgentGamification.ts',32,61,'controle positivo: consultas reais existentes no outro painel')],
    ['Conectar a view ao estado autorizado do usuário e distinguir carregamento, ausência real, erro e demonstração.',
     'Se os mocks permanecerem como demonstração, identificar esse modo e não apresentá-los como saldo ou desempenho da conta.',
     'Vincular resgate à operação autorizada/idempotente confirmada e atualizar o saldo, ou remover a promessa de recompensa real.',
     'Conferir conta nova, conta com conquistas e reabertura após resgate: valores e datas devem vir da fonte correspondente e não se repetir por remontagem.'],
    ['Não se afirma uso dessas pontuações em decisões trabalhistas. O efeito comprovado é a atribuição visual de desempenho e saldo inexistentes na fonte consumida.',
     'Leaderboard e AchievementsPanel têm consultas reais; não se afirma que toda a infraestrutura de gamificação seja mock.',
     'Nenhuma conquista real foi criada, reivindicada ou alterada.'])

add(43, 'Mini-games anunciam ganho de XP sem consumidor que credite a recompensa',
    'Dashboard GamificationSection → DashboardWidgetRenderer mini-games → TrainingMiniGames sem onXPEarned → conclusão do jogo → toast Você ganhou XP.',
    'Usuário abre o widget de mini-games e conclui um dos jogos implementados com pontuação positiva.',
    'A única montagem produtiva de TrainingMiniGames não fornece onXPEarned. handleGameComplete chama opcionalmente essa prop e sempre informa Você ganhou N XP. Seus únicos writes efetivos são score/estado local e miniGameHighScores no localStorage, sem usuário, RPC ou integração ao saldo agent_stats. Assim a conclusão anuncia recompensa, mas nenhuma operação de crédito é executada no caminho atual. O componente oferecer callback não comprova que ele esteja conectado.',
    [evidence('src/components/dashboard/overview/GamificationSection.tsx',18,40,'widget visível encaminhado ao renderer'),
     evidence('src/components/dashboard/DashboardWidgetRenderer.tsx',144,148,'único consumidor omite onXPEarned'),
     evidence('src/components/gamification/TrainingMiniGames.tsx',11,44,'callback opcional, writes locais e confirmação incondicional'),
     evidence('src/components/gamification/MiniGameDialogs.tsx',87,95,'conclusão do quiz com pontuação e XP'),
     evidence('src/hooks/gamification/mutations.ts',8,20,'operação real de XP existe, mas não está ligada ao mini-game')],
    ['Definir se XP do jogo é apenas pontuação local ou recompensa da conta e comunicar essa distinção na interface.',
     'Se houver crédito real, conectar a conclusão ao contrato autorizado e idempotente e confirmar somente após persistência; não confiar apenas em número fornecido pelo cliente.',
     'Conferir saldo antes/depois e após reload, conclusão repetida e falha do crédito. O texto de sucesso deve corresponder ao efeito confirmado.',
     'Separar recordes locais por usuário quando a apresentação for pessoal e validar o formato salvo antes de carregar.'],
    ['O jogo e o recorde local existem; a falha não é ausência de toda mecânica de treinamento.',
     'Não houve invocação real da RPC de XP. Políticas e autorização dessa RPC pertencem à análise SQL, e sua existência não foi tratada como garantia de crédito pelo frontend.',
     'O problema de fechar o jogo seguinte é independente e está em AUTH044.'])

add(44, 'Speed Typing encerrado conclui o jogo seguinte e grava seu recorde sem jogá-lo',
    'TrainingMiniGames mantém os três componentes montados → SpeedTypingGame timer chega a zero → onComplete inline muda no rerender → effect de conclusão roda mesmo fechado → handleGameComplete captura novo selectedGame.',
    'Na mesma montagem do widget, o usuário conclui Speed Typing e depois abre outro jogo, por exemplo Quiz.',
    'SpeedTypingGame não redefine isActive ao concluir/fechar e seu effect chama onComplete sempre que timeLeft===0, sem gate isOpen nem marca de conclusão. O pai recria handleGameComplete em cada render e mantém o componente montado mesmo com o Dialog fechado. Ao selecionar Quiz, a nova closure continua sendo chamada pelo Speed Typing já encerrado: ela usa selectedGame=quiz, grava o score de digitação como recorde do Quiz, anuncia sua conclusão e fecha o diálogo recém-aberto. A prova offline terminou uma frase de33 pontos, observou duas conclusões e depois um Quiz fechado com33 pontos e16 XP anunciados, sem responder pergunta.',
    [evidence('src/components/gamification/MiniGameDialogs.tsx',18,37,'state do timer e effect sem gate de abertura/conclusão'),
     evidence('src/components/gamification/TrainingMiniGames.tsx',25,44,'callback usa selectedGame atual, salva recorde e fecha jogo'),
     evidence('src/components/gamification/TrainingMiniGames.tsx',53,58,'seleção do próximo jogo'),
     evidence('src/components/gamification/TrainingMiniGames.tsx',78,80,'componentes permanecem montados e callback inline compartilhado')],
    ['Encerrar/cancelar timer e marcar cada partida como concluída uma única vez, considerando isOpen e uma identidade estável da partida.',
     'Vincular score à partida que o produziu, sem depender do selectedGame da closure recriada posteriormente.',
     'Conferir terminar/fechar digitação, abrir Quiz e Emoji, reabrir digitação e rerender do dashboard: não pode haver conclusão, crédito ou recorde sem evento válido da respectiva partida.',
     'Cancelar callbacks pendentes no fechamento/desmontagem e preservar os jogos novos de conclusões tardias dos anteriores.'],
    ['P-AUTH-11 executa declarações reais e constantes fixadas com scheduler React sintético de useState/useEffect e60 ticks virtuais. Outros jogos são elementos stub; nenhuma resposta do Quiz é submetida.',
     'O teste não é navegador/E2E e não comprova frequência em produção. Ele reproduz o ordenamento e os writes locais sem rede ou banco.',
     'Não é inflação de saldo real: AUTH043 documenta que o consumidor atual não credita XP no banco.'])
f44 = next(f for f in supp['new_findings'] if f['id']=='R2-AUTH-044')
f44['status'] = 'CONFIRMED_OFFLINE_PROBE'
f44['offline_probes'] = ['P-AUTH-11']
gamification_result = str(BASE / 'probes/auth/gamification-results.json')
if gamification_result not in supp.setdefault('probe_results', []):
    supp['probe_results'].append(gamification_result)

supp['external_sources'] = [dict(
    url='https://docs.postgrest.org/en/stable/references/api/resource_embedding.html',
    purpose='Resource embedding é determinado pelas FKs; !fk seleciona relação existente, R2-AUTH-033',
    retrieval_ref='turn42view0'),dict(
    url='https://supabase.com/docs/reference/javascript/insert',
    purpose='Contrato de retorno data/error do cliente Supabase, R2-AUTH-034',
    retrieval_ref='turn50view0'),dict(
    url='https://tanstack.com/query/latest/docs/framework/react/guides/mutations',
    purpose='Callbacks de mutation conforme promessa resolvida/rejeitada, R2-AUTH-034',
    retrieval_ref='turn50view1'),dict(
    url='https://www.postgresql.org/docs/current/functions-comparison.html',
    purpose='Comparações ordinárias com NULL produzem resultado desconhecido; efeito do p_until nulo em R2-AUTH-041',
    retrieval_ref='turn55view0')]

patch7 = dict(id='R2-AUTH-007', append=dict(
    evidence=[evidence('src/components/security/RejectResetDialog.tsx',30,40,'promessa de notificação por email na rejeição'),
              evidence('supabase/functions/approve-password-reset/index.ts',48,64,'rejeição só atualiza pedido e responde sucesso')],
    limitations=['O ramo de rejeição também anuncia notificação por email no diálogo, mas o handler apenas atualiza a solicitação; nenhum transporte de rejeição foi localizado.']))
supp['amendments'] = [p for p in supp['amendments'] if p['id'] != 'R2-AUTH-007'] + [patch7]

patch12 = dict(id='R2-AUTH-012', append=dict(
    evidence=[evidence('src/components/contacts/ContactsTable.tsx',218,237,'menu ativo Gerenciar etiquetas sem handler'),
              evidence('src/components/contacts/ContactContentArea.tsx',131,138,'consumidor de produção da tabela')],
    limitations=['A tabela da página Contatos também oferece Gerenciar etiquetas sem handler; edição, chat e exclusão no mesmo menu possuem handlers reais e gates conferidos. É mais uma superfície do mesmo no-op de tags, não uma contagem adicional.']))
supp['amendments'] = [p for p in supp['amendments'] if p['id'] != 'R2-AUTH-012'] + [patch12]

# Full bodies actually read since the preceding checkpoint.
full = {
 'src/hooks/crm/useAgentPresence.ts': 'join, joinSeq/cancelamento, heartbeat, presença própria e leave',
 'src/hooks/system/useRateLimitLogs.ts': 'query limitada, polling/abort, cálculo de estatísticas e erro',
 'src/components/contacts/ContactEngagementScore.tsx': 'calculateEngagement, uso de recência/frequência/volume e representação',
 'src/components/security/DevicesPanel.tsx': 'sessões confiáveis, handlers e promessas de encerramento',
 'src/components/security/DeviceCard.tsx': 'SessionCard, dispositivo atual, trust/remove e confirmação',
 'src/hooks/system/useUserSettings.ts': 'fetchSettings, defaults, ciclo user.id, updateSettings e saveSettings',
 'src/hooks/system/useGlobalSettings.ts': 'fetchSettings, getSetting, updateSetting, addSetting e montagem',
 'src/hooks/system/useDownloadPermission.ts': 'query por usuário e fail-closed do flag',
 'src/hooks/crm/useContactsSearch.ts': 'filtros/debounce, paginação, lastMessageMap, canDeleteMap, enriquecimento e clearSearch',
 'src/hooks/crm/useContactsKpi.ts': 'aggregateKpi, séries/deltas, fetchKpiRows e consulta agregada',
 'src/components/contacts/ContactContentArea.tsx': 'estados vazios, escolha de views, seleção e consumidores de dados',
 'src/hooks/system/useCRUD.ts': 'queries e mutations genéricas; sem consumidor ativo localizado',
 'src/hooks/system/useSupabaseMutation.ts': 'wrapper de mutation, toast/erro; sem consumidor ativo localizado',
 'src/hooks/system/useFeatureFlag.ts': 'query, gate usuário, defaults e polling',
 'src/hooks/system/useUrlFilters.ts': 'parse/set/clear URL, preservação de outras chaves e dates',
 'src/components/contacts/ContactAnalyticsDashboard.tsx': 'distribuições, top empresas/tags, crescimentos e escopo dos rótulos',
 'src/components/contacts/CRMFiltersPanel.tsx': 'filtros e opções/cap da lista',
 'src/hooks/crm/contactsAggregates.ts': 'invalidação agregada, preferência de legados e política de refetch',
 'src/components/contacts/ContactKanbanView.tsx': 'estado otimista, confirmedTypes, inFlightRef, mutation/rollback e drag',
 'src/components/inbox/ImagePreview.tsx': 'portal, canDownload, download, resolução de URL e preview',
 'src/components/admin/AdminView.tsx': 'gate admin/staff, handlers, todos os formulários e tabs de conteúdo',
 'src/components/settings/SettingsView.tsx': 'settings pessoais/staff, carregamento/salvar e todas as tabs',
 'src/components/settings/GlobalSettingsSection.tsx': 'toggles, input por request, persistência e promessas',
 'src/components/settings/IntegrationKeysSection.tsx': 'campo de chave, visualização, UPSERT e feedback',
 'src/components/team-chat/NewConversationDialog.tsx': 'seleção/limpeza de membros e departamento, criação, pendência e UI completa',
 'src/components/team-chat/TeamConversationList.tsx': 'filtros, badges/membros, entrada de gestão e props opcionais',
 'src/components/team-chat/teamChatParts.tsx': 'formatação, tipos de mídia, resolução assinada e volume dos players',
 'src/components/team-chat/TeamChatA11y.tsx': 'skip link/announcer, foco e reduced motion; sem consumidor ativo localizado',
 'src/components/team-chat/TeamMemberProfileHeader.tsx': 'birthday, roles, info rows, header de grupo e status por is_active',
 'src/components/team-chat/department-management/DepartmentAuditView.tsx': 'auditoria, vocabulário de ações e estados vazios',
 'src/components/team-chat/department-management/DepartmentInvitesView.tsx': 'consulta, cópia/criação/exclusão de convite e gate isAdmin',
 'src/components/team-chat/department-management/DepartmentMembersView.tsx': 'membros/outros, busca e mutações de departamento',
 'src/components/team-chat/department-management/DepartmentWhatsAppView.tsx': 'modo, carregamento de URL, segredos sem prefill e payload de salvar',
 'src/components/mfa/MFAEnroll.tsx': 'enroll, QR/secret copy, verificação automática e estados de navegação',
 'src/components/security/PasskeyDialogs.tsx': 'registro, rename/delete e fechamento/pending',
 'src/components/security/RejectResetDialog.tsx': 'estado reason, rejeição e promessa de notificação',
 'src/components/security/QuarantineBadge.tsx': 'mapping de decisão, montagem/tooltip e ausência de dado',
 'src/components/security/RateLimitRealtimeAlerts.tsx': 'polling/diff, refs de áudio e dismiss/UPDATE',
 'src/components/security/AuditLogDashboard.tsx': 'query/filtros, classificação de ações, totais e renderização completa',
 'src/components/security/SecurityView.tsx': 'todas as tabs/gates, montagem de alertas e rotas administrativas',
 'src/components/auth/PasswordInput.tsx': 'input/reveal, props e acessibilidade',
 'src/components/auth/PasswordStrengthMeter.tsx': 'requirements/hash, debounce, consultas em voo e veredito visual',
 'src/pages/admin/RolesPage.tsx': 'gate admin, listas, dialogs e permission/visibility tabs',
 'src/pages/admin/RateLimitDashboard.tsx': 'gates, métricas/unidades, listas, limites de exibição e tabs',
 'src/components/admin/AdminAuditTable.tsx': 'atribuição de usuário, detalhes e renderização de ações',
 'src/components/contacts/ContactSearchWithSuggestions.tsx': 'input, sugestões, recentes, persistência e limpeza',
 'src/components/contacts/ContactResultsSummary.tsx': 'contagens, seleção, paginação e early return vazio',
 'src/components/contacts/ContactPurchaseHistory.tsx': 'query limitada, erro/estado, totais, moeda e expansão',
 'src/components/contacts/ContactAdvancedFilters.tsx': 'empresa/cargo/tags/período e capacidades opcionais IA',
 'src/components/contacts/FilterPresets.tsx': 'validação/migração de presets, armazenamento e aplicação',
 'src/hooks/crm/useCRMAdminAccess.ts': 'query por usuário, RPC de acesso administrativo e fail-closed',
 'src/hooks/crm/useVisibleAgents.ts': 'query por usuário, RPC de agentes visíveis e propagação de erro',
 'src/hooks/crm/useAgentsLite.ts': 'lista direta de profiles, query key, RLS e consumidor encaminhado ao inbox',
 'src/hooks/crm/useExternalEmpresas.ts': 'gate CRM, opções externas e cache da lista',
 'src/hooks/crm/useExternalCargos.ts': 'gate CRM, opções externas e cache da lista',
 'src/hooks/system/useResourcePrefetch.ts': 'cache/pending compartilhados, líder/seguidores, cancelamento de montagem e utilitários; sem consumidor ativo',
 'src/hooks/system/useNavigationHistory.ts': 'URL view, eventos, push/replace, back/forward, estado e history de navegação',
 'src/hooks/crm/useContactPurchases.ts': 'consulta por contato, ordenação, keys e estados de retorno',
 'src/hooks/crm/useContactStats.ts': 'delegação ao serviço, query key e refetch',
 'src/hooks/crm/useContactSummaryNote.ts': 'consulta e UPDATE sem retorno de linha, invalidação e contrato do resumo',
 'src/hooks/crm/useContactNotes.ts': 'consulta com identidade, categorias, três mutations, invalidação e retorno error não inspecionado',
 'src/components/inbox/tabs/NotesTab.tsx': 'todas as categorias, rascunhos, autoria, promises, tarefas e resumo comercial',
 'src/components/inbox/contact-details/sidebar/professionalFallback.ts': 'campos profissionais disponíveis e ausência de inferência de departamento',
 'src/components/inbox/contact-details/AIInsightsWidget.tsx': 'gate CRM, montagem da query e rendering de insights',
 'src/components/inbox/contact-details/CompactContactHeader.tsx': 'identidade, avatar, VIP e empresa',
 'src/components/inbox/contact-details/LastActivityWidget.tsx': 'consulta de timeline, recorte das três atividades e estado vazio',
 'src/components/inbox/contact-details/SLAAndAITagsSection.tsx': 'tempos SLA, resposta/violação, tags e confiança IA',
 'src/components/inbox/contact-details/EvolutionContactProfileSection.tsx': 'estados de configuração/erro/carga, perfil empresarial, device e links',
 'src/components/inbox/contact-details/WhatsAppStatusSection.tsx': 'status/presença, recarga, empty/error e remontagem do viewer por sessão',
 'src/components/inbox/contact-details/Contact360Helpers.tsx': 'RFM, empresa, cliente, contato, interações, redes, endereço, canal e radar',
 'src/components/inbox/contact-details/StoryViewer.tsx': 'identificação de mídia, navegação, loading/cancelamento, resolução da instância e renderização',
 'src/hooks/integrations/useEvolutionContactProfile.ts': 'variantes JID, lookup externo, montagem/erro e retorno de perfil',
 'src/hooks/integrations/useWhatsAppStatus.ts': 'resolução da instância, matching por telefone/nome, actions e presença fixa',
 'src/hooks/ui/useScreenProtection.ts': 'atalhos/copy/print/blur, configuração local, instalação e cleanup de listeners',
 'src/components/notifications/ScreenProtectionToggle.tsx': 'preferência local e evento compartilhado, sem promessa de controle administrativo',
 'src/components/team-chat/TeamMessageItem.tsx': 'edição/resposta/mídia/reação/TTS/status, gates de autoria e confirmação de exclusão',
 'src/components/team-chat/TeamMessageReactionsWrapper.tsx': 'barra de reação, picker e toggle/fechamento',
 'src/hooks/team-chat/useParticipantStats.ts': 'limite 500, agrupamento, leitura de perfil e status de mensagem; consumidor dormente',
 'src/hooks/team-chat/useTeamPerformance.ts': 'janela 30min, contagens e média de gaps; consumidor dormente',
 'src/components/team-chat/TransferConversationDialog.tsx': 'seleção de destinatário, confirmação, mutations, pending e lista; montagem pendente',
 'src/components/team-chat/ParticipantStatsGraph.tsx': 'simulação identificada, séries e estados de consulta; montagem pendente',
 'src/components/team-chat/TeamPerformancePanel.tsx': 'consulta, métricas, export JSON e gráfico; montagem pendente',
 'src/hooks/team-chat/teamChatTypes.ts': 'contratos de conversation/member/message e campos opcionais',
 'src/hooks/team-chat/teamMessageStatus.ts': 'normalização de estados e fallback sent',
 'src/hooks/team-chat/index.ts': 're-exports dos hooks e tipos',
 'src/components/admin/AdminCRMDashboard.tsx': 'health com validação/erro, métricas externas, top clientes, RFM, vendas e navegação',
 'src/components/admin/MediaMigrationTool.tsx': 'invoke da migração, erro, resultado, progresso/contagens e histórico da sessão',
 'src/components/admin/PublicApiDashboard.tsx': 'API explicitamente suspensa por segurança; ausência de mutation',
 'src/App.tsx': 'rotas e providers globais, lazy hooks, gates e hierarquia de montagem',
 'src/components/admin/CrisisRoom.tsx': 'queries, unidades, thresholds, estado de crise e ciclo de atualização',
 'src/components/admin/TrainingMode.tsx': 'cenários, sessões, gravações, respostas, sorteio de nota e feedback',
 'src/components/admin/SupervisorCopilot.tsx': 'perguntas, contexto insuficiente, invoke de IA, erros e histórico; IA-METRICS-001 mantido',
 'src/hooks/system/useNotificationSettings.ts': 'defaults, mapeamento/SELECT, cache optimistic, UPSERT, reset e quiet hours',
 'src/hooks/system/useNotifications.ts': 'consulta, estados, realtime, contagem e mutations de leitura/exclusão/criação',
 'src/components/notifications/NotificationSettingsPanel.tsx': 'preferências globais/por tipo, teste de som, permissão browser e reset',
 'src/components/notifications/NotificationTypeCards.tsx': 'SoundSelector, toggles por evento, sentimento, horários e handlers',
 'src/hooks/realtime/useRealtimeNotifications.ts': 'gate por contato/lida, som/popup, quiet hours, callbacks e refs',
 'src/hooks/sla/useSLANotifications.ts': 'subscriptions INSERT/UPDATE, dedup, consulta do contato, som/popup e cleanup',
 'src/hooks/inbox/useSentimentAlerts.ts': 'política canônica Edge, dedup, som por menção, popup e getRecentAlerts',
 'src/lib/secureRandom.ts': 'float, rejection sampling de inteiro e caracteres; função de sorteio do treinamento',
 'src/components/notifications/NotificationsPopover.tsx': 'contador, lista, marcação individual/global e estado vazio',
 'src/components/notifications/NotificationItem.tsx': 'mapa de tipos, alarmes, clique de marcar lida e rendering',
 'src/components/notifications/SLANotificationProvider.tsx': 'montagem do hook e children',
 'src/components/contacts/ContactToolbar.tsx': 'filtros, ordenações, presets, legados, gate de merge e opções da view',
 'src/components/contacts/ContactsTable.tsx': 'sort local, seleção, cells e menu com handlers/gates e tags sem handler',
 'src/components/contacts/ContactGroupedList.tsx': 'grupo por empresa, ordenação por quantidade, collapse e campos das linhas',
 'src/components/contacts/ContactListItem.tsx': 'empresa, links wa.me/mailto, seleção, ações e exclusão autorizada',
 'src/components/contacts/ContactCard.tsx': 'recência de mensagem e fallback de cadastro, tipos, ações e gate de exclusão',
 'src/components/contacts/CRMContactCard.tsx': 'seleção, campos externos, vendedor separado e scores',
 'src/components/contacts/CompanyLogo.tsx': 'iniciais/cor determinística, erro de imagem e reset por URL',
 'src/components/contacts/ContactCompareDialog.tsx': 'comparação de campos, tags e datas dos contatos selecionados',
 'src/components/contacts/ContactViewSwitcher.tsx': 'modos, callbacks de densidade e agrupamento, todas as opções',
 'src/components/contacts/ContactMapView.tsx': 'grupos DDD, preciseContacts, contagens, cartões e props para mapa',
 'src/components/contacts/ContactRegionMap.tsx': 'token/criação/cleanup Mapbox, bolhas, pinos precisos, limites e legendas',
 'src/components/contacts/contactRegionGeo.ts': 'coordenadas de referência estáticas e lookup/fallback nulo',
 'src/components/contacts/getRegionFromPhone.ts': 'prefixos de país, DDD e fallback de região',
 'src/components/contacts/types.ts': 'contratos de Contact, campos de endereço e flags de capacidade',
 'src/components/contacts/ContactEmptyState.tsx': 'estados de busca/base vazia e ações condicionais',
 'src/components/contacts/ContactKpiCard.tsx': 'CountUp, reduced motion, Sparkline, deltas e estados',
 'src/components/contacts/ContactStatsCards.tsx': 'props dos KPIs e skeleton de ausência/carregamento',
 'src/components/contacts/ContactTypeTabs.tsx': 'tipos/contagens, ordem, callbacks e animação reduzida',
 'src/components/contacts/ContactsSkeleton.tsx': 'estrutura visual dos modos e estados de carga',
 'src/components/contacts/HighlightText.tsx': 'escape RegExp, split e rendering seguro de destaque textual',
 'src/components/contacts/contactTypeConfig.tsx': 'configuração tipada de tipos, cores, rótulos e render de ícones',
 'src/components/contacts/contactTypeOrder.ts': 'ordem canônica e conjunto de tipos válidos',
 'src/components/crm360/CRM360StatsCards.tsx': 'contagens estimadas externas, erros e cards de tabelas',
 'src/components/crm360/DataExplorerTable.tsx': 'ordenação, paginação, loading/erro, células e ações de criação',
 'src/components/crm360/crm360TabsConfig.ts': 'formatadores de data/moeda/objeto/booleano e contrato de tabs',
 'src/components/crm360/crm360TabsData.ts': 'todas as tabelas/colunas externas, campos editáveis e rótulos',
 'src/components/auth/HeroBenefits.tsx': 'marketing e métricas estáticas; nenhuma comprovação externa de indicadores',
 'src/components/auth/SocialProof.tsx': 'selos/claims estáticos; certificação e disponibilidade não verificadas',
 'src/components/admin/AIUsageDashboard.tsx': 'consumidor, filtros, totais, gráficos, usuários, logs e bloco de custo',
 'src/components/admin/AIUsageLogsTab.tsx': 'lista real paginada, total, cabeçalhos e estados',
 'src/components/admin/AIUsageUsersTab.tsx': 'gráfico top10 e tabela dos usuários agregados recebidos',
 'src/components/admin/PlaybooksManager.tsx': 'consultas, editor/etapas, save com error e delete sem error, permissões staff corroboradas',
 'src/components/admin/telemetry/TelemetryCharts.tsx': 'agregações por balde, médias/máximos, top8 e tabela de consultas',
 'src/hooks/analytics/useAIUsageDashboard.ts': 'janela memoizada, queries periódicas, resumo/custo/logs, paginação, formatadores e refetch',
 'src/hooks/auth/index.ts': 'barrel de auth; re-export não implica consumo dos símbolos',
 'src/hooks/crm/index.ts': 'barrel de CRM; re-export não implica integração de componente dormente',
 migration('20261003102707'): 'função de custo integral, janela, vigência/prioridade de tarifas, moedas, agregação, grants e invoker',
 'src/components/ai/AutoTicketClassifier.tsx': 'queries, agrupamento inline, batch/erro/sucesso, toggle sem efeito e rendering; ampliação de IA-METRICS-001',
 'src/components/ai/ticketClassification.ts': 'regras e agrupamento com validação de linhas; helper sem consumidor produtivo localizado',
 'src/components/ai/ChurnPredictionDashboard.tsx': 'todos os fatores, consultas/caps, invoke e resultado descartado, UI de risco; IA-METRICS-001 mantido',
 'src/components/ai/churnRisk.ts': 'helper de score e clamp de datas; sem consumidor produtivo localizado',
 'src/components/gamification/GamificationProvider.tsx': 'context/noop, fila, todas as triggers e mutations, level-up; provider sem montagem localizada',
 'src/components/gamification/MiniGameDialogs.tsx': 'três jogos, callbacks, timers/reset, comparação de respostas e efeitos de fechamento',
 'src/components/gamification/TrainingMiniGames.tsx': 'seleção, persistência local, conclusão, crédito opcional e montagem permanente dos jogos',
 'src/components/gamification/miniGamesData.ts': 'catálogo de quatro jogos, frases, quiz e desafios emoji',
 'src/components/gamification/AchievementsSystem.tsx': 'mocks, timer/identidade, XP/nível, claim local, versões compacta/completa e diálogo',
 'src/components/gamification/AchievementsPanel.tsx': 'dados reais, filtros/períodos locais, ordenação, tipos, lista e limites da query',
 'src/components/gamification/DemoAchievements.tsx': 'consumidor do contexto, triggers de demonstração, promessa de salvar e navegação para painel real',
 'src/components/gamification/AchievementDetailDialog.tsx': 'detalhes/progresso, gate isNew e chamada onClaim/onClose',
 'src/components/gamification/AchievementsStats.tsx': 'agregados da lista, nível/XP, badges recentes e comparação de datas',
 'src/components/gamification/AchievementBadge.tsx': 'todos os mapas/configs, normal/mini, fallback de tipo, data e rendering',
 'src/components/gamification/AchievementToast.tsx': 'tipos/configs, partículas, timer e cleanup, fechar, mensagens/XP e hook local',
 'src/hooks/gamification/useAgentGamification.ts': 'perfil por Auth UUID, queries por profileId, cap20, erros e mutations',
 'src/hooks/gamification/mutations.ts': 'cinco RPCs, parâmetros, tratamento de retorno/erro e invalidação por perfil',
 'src/hooks/gamification/useLeaderboard.ts': 'período explícito, RPC/achievements, mapeamento, refresh/realtime e conclusão tardia já coberta',
 'src/hooks/gamification/types.ts': 'contratos de stats/achievement e vocabulário dos tipos',
 'src/hooks/gamification/levelUtils.ts': 'nível, XP necessário e progresso entre níveis',
 'src/hooks/gamification/index.ts': 're-exports de tipos, funções e hooks',
 'src/components/dashboard/overview/GamificationSection.tsx': 'widgets visíveis, filtro de staff, ordem e renderer da seção colapsável',
 'supabase/functions/ai-classify-tickets/index.ts': 'autenticação/caller RLS, guardas, leitura/regras de tags e resultado sem persistência; coordenação com infra',
}
for path, symbols in full.items():
    n = len((SRC / path).read_text().splitlines())
    evidence(path, 1, n, symbols)
    supp['reviewed_files'][path] = dict(review_level='semantic', symbols=[symbols],
        ranges=[dict(start_line=1, end_line=n, symbol=symbols)])

targeted = {
 'src/components/email/EmailChatInbox.tsx': [(30,175,'cross-review do ciclo callback inline/estado, encaminhado ao root')],
 'src/components/email/EmailChatThread.tsx': [(35,157,'cross-review do useEffect dependente de callback, encaminhado ao root')],
 'src/components/contacts/ContactSearchWithSuggestions.tsx': [(28,154,'input/sugestões/recentes; X cancela debounce via onChange')],
 'supabase/schema-manifest.json': [(6655,6672,'grant profiles UPDATE authenticated'),(4558,4566,'FK user_roles conservada no snapshot')],
 migration('20260405230710'): [(1,49,'policies own UPDATE e proteção restritiva')],
 migration('20260830080000'): [(1,71,'is_admin, policies de permissões e trigger de privilégio')],
 'supabase/functions/elevenlabs-tts/index.ts': [(1,53,'consumer da chave de ambiente e boundary de chamada')],
 'src/pages/Auth.tsx': [(247,248,'PasswordStrengthMeter no cadastro')],
 'src/integrations/supabase/types.ts': [(8838,8858,'relacionamentos user_roles exportados')],
 migration('20251215025014'): [(1,20,'FK user_roles para auth.users')],
 migration('20260924125400'): [(18,76,'writer e cleanup da função órfã de auditoria de roles')],
 migration('20260409224329'): [(51,54,'trigger de auditoria de user_roles')],
 'src/providers/AppProviders.tsx': [(57,90,'cross-review do lifetime AuthProvider/CallSessionProvider')],
 'src/providers/CallSessionProvider.tsx': [(235,477,'provider de chamada sem dependência da identidade, cross-review encaminhado ao root')],
 'src/hooks/communication/useSipClient.ts': [(51,100,'cleanup não encerra UA; root detém achado de lifetime SIP')],
 'src/components/inbox/chat/ConversationTabContent.tsx': [(111,117,'consumidor ativo de NotesTab')],
 'src/services/contact.service.ts': [(99,154,'fetchNotes e mutations devolvendo resposta integral')],
 'src/components/email/EmailContactPanel.tsx': [(260,337,'contexto de empresa e consumidor de notas; restante pertence ao root')],
 'supabase/functions/evolution-api/index.ts': [(714,738,'actions de histórico/status e resposta GO'),(835,863,'send-chat-presence envia POST de presença')],
 'supabase/functions/_shared/evolution-sync-actions.ts': [(1,110,'normalização/sync de contato e notSupported GO; restante pertence a providers'),(339,341,'jsonRes notSupported usa status padrão HTTP200')],
 migration('20260909200000'): [(154,190,'policies SELECT/INSERT/UPDATE/DELETE das notas')],
 migration('20261003072707'): [(35,78,'janela temporal e agregação de uso de IA')],
 'src/pages/ViewRouter.tsx': [(81,118,'registro das views IA e consumidor de conquistas')],
 'src/pages/lazyViews.ts': [(40,41,'imports lazy de churn/classificador'),(52,61,'imports lazy de CRM, consumo IA e conquistas')],
 'src/components/dashboard/DashboardWidgetRenderer.tsx': [(135,152,'consumidores de gamificação e mini-games sem onXPEarned')],
}
for path, ranges in targeted.items():
    record = supp['reviewed_files'].setdefault(path, dict(review_level='targeted', symbols=[], ranges=[]))
    if record['review_level'] == 'semantic':
        continue
    for a,b,symbol in ranges:
        evidence(path,a,b,symbol)
        r = dict(start_line=a,end_line=b,symbol=symbol)
        if r not in record['ranges']:
            record['ranges'].append(r)
        if symbol not in record['symbols']:
            record['symbols'].append(symbol)

extra_rejected = [
 dict(id='D-AUTH-15', paths=['src/hooks/system/useCRUD.ts','src/hooks/system/useSupabaseMutation.ts'],
      status='NO_ACTIVE_CONSUMER', reason='Utilitários genéricos têm limitações de query key/count/retorno de erro, mas a busca encontrou apenas definição, re-export e exemplo. Não contados como falha ativa de cache ou mutation.'),
 dict(id='D-AUTH-16', paths=['src/hooks/team-chat/useTeamChatMutations.ts','src/components/team-chat/useTeamChatPanel.ts'],
      status='ACTIVE_FLOW_DISTINGUISHED_FROM_DORMANT_RPC', reason='Peer SQL identificou search_team_messages sem filtro is_deleted. A UI atual não chama essa RPC e faz DELETE físico; a pesquisa local do Panel não prova reexposição de conteúdo soft-deleted. Resultado encaminhado ao agente SQL.'),
 dict(id='D-AUTH-17', paths=['src/hooks/system/useUserSettings.ts'],
      status='IDENTITY_SWITCH_PRECONDITION_UNVERIFIED', reason='Hook conserva settings entre user.id e não cancela fetch anterior; save usa usuário atual. O fluxo normal de logout desmonta a view, portanto não se afirma cópia entre contas sem demonstrar troca direta de identidade com componente preservado. Revisão do mecanismo feita; classificação ativa retida.'),
 dict(id='D-AUTH-18', paths=['src/hooks/crm/useContactsSearch.ts','src/components/contacts/ContactContentArea.tsx'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='clearSearch não cancela debounce pendente. Se resultado anterior vazio mantém botão de limpar e usuário digita outro termo e clica antes dos 400ms, o callback pode recolocar termo no filtro com input vazio. O X do input chama handleSearchChange e cancela corretamente. Registrado como observação de UI de baixo impacto, não agregado aos achados materiais.'),
 dict(id='D-AUTH-19', paths=['src/components/team-chat/TeamMemberProfileHeader.tsx','src/hooks/team-chat/useTeamMemberDetails.ts'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='DirectProfileHeader mostra Online/Offline pelo profiles.is_active, que indica ativação administrativa, e não presença. Para admin/supervisor que consegue ler o colega, conta habilitada sem sessão aparece Online. Sem impacto provado em roteamento; observação visual separada de AUTH020 e da RLS em AUTH011.'),
 dict(id='D-AUTH-20', paths=['src/pages/admin/RateLimitDashboard.tsx','src/hooks/system/useRateLimitLogs.ts'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='TotalRequests soma request_count; Bloqueados e percentual contam linhas; Alertas Ativos é o número de logs históricos blocked, sem consulta de alertas/resolução. A aba promete últimas100 mas renderiza somente20 sem paginação. A unidade e o recorte do painel não são coerentes. Não altera enforcement; nenhum dado real foi consultado.'),
 dict(id='D-AUTH-21', paths=['src/components/contacts/ContactPurchaseHistory.tsx'],
      status='STATIC_PRESENTATION_LIMIT', reason='Histórico busca no máximo20 e soma os não-cancelados como Valor total; não identifica o recorte. Lê currency mas rotula qualquer quantia como R$. Moedas diferentes dependem de dados/produtor não validados; não se afirma soma financeira real incorreta no ambiente. Carga/erro também não são separados de Nenhuma compra. Consulta e cálculos revisados integralmente.'),
 dict(id='D-AUTH-22', paths=['src/components/security/RateLimitRealtimeAlerts.tsx'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='Polling só chama setAlerts e atualiza lastKnownIds se surgir ID novo. Resolver todos os alertas em outra sessão produz fresh=[] e conserva alertas antigos até remontagem/novo evento. Dismiss oculta antes do UPDATE e ignora falha. Gate admin existe; não se afirma incidente de entrega nem ausência de todo alerta.'),
 dict(id='D-AUTH-23', paths=['src/components/security/AuditLogDashboard.tsx'],
      status='STATIC_PRESENTATION_LIMIT', reason='Consulta só últimos200, pesquisa texto somente nesse subconjunto e rotula data.length Total de Logs sem explicitar recorte. Erro conserva listas/stats antigos ou zero sem aviso. Os fatos de vocabulário com efeito comprovado em mudanças de acesso estão em AUTH032; retenção/paginação integral não foi executada.'),
 dict(id='D-AUTH-24', paths=['src/components/team-chat/TeamChatA11y.tsx'],
      status='NO_ACTIVE_CONSUMER', reason='SkipLink, Announcer, useFocusTrap e usePrefersReducedMotion têm implementação, mas nenhum consumidor de produção foi localizado por busca de símbolo. Não contar como acessibilidade integrada; detalhes de foco dinâmico ficam para o aceite de integração.'),
 dict(id='D-AUTH-25', paths=['src/hooks/system/useResourcePrefetch.ts'],
      status='NO_ACTIVE_CONSUMER', reason='Cache de prefetch global não inclui identidade e utilitários de leitura não verificam TTL; a busca de símbolos achou definições/re-export, sem consumidor de produção. Não é uma exposição ativa comprovada. O usePrefetch de outros módulos é função diferente e não foi confundido com esta implementação.'),
 dict(id='D-AUTH-26', paths=['src/hooks/ui/useScreenProtection.ts','src/components/notifications/ScreenProtectionToggle.tsx'],
      status='LOCAL_UI_CONTROL_LIMIT', reason='Proteção de tela instala efeitos locais e pode ser desativada pelo próprio usuário; não equivale a DLP ou bloqueio de captura pelo sistema operacional. Não foi apresentado como bypass de autorização, porque essa UI oferece toggle pessoal e dados já são legíveis ao usuário. Remoção de listeners/overlay no cleanup foi verificada.'),
 dict(id='D-AUTH-27', paths=['src/components/admin/AdminCRMDashboard.tsx'],
      status='STATIC_PRESENTATION_LIMIT', reason='Top5 clientes usa vendedor_nome como nome; distribuição RFM agrega no máximo200 registros e não identifica amostra. Erros das métricas viram zero/vazio, mas IntegrationHealth valida shape e mostra Health check indisponível. Não se afirma dado financeiro real incorreto; recorte externo não executado.'),
 dict(id='D-AUTH-28', paths=['src/components/admin/SupervisorCopilot.tsx'],
      status='PRIOR_FINDING_CONFIRMED_NO_NEW_COUNT', reason='IA-METRICS-001 anterior já cobre contexto insuficiente para SLA/backlog/performance. Leitura integral confirma o mesmo problema e erros de consultas tratados como zero; nenhum achado novo contado por esta repetição.'),
 dict(id='D-AUTH-29', paths=['src/hooks/crm/useContactSummaryNote.ts','src/components/inbox/tabs/NotesTab.tsx'],
      status='STRUCTURAL_AUTH_MISMATCH_REJECTED', reason='Resumo comercial faz UPDATE sem count e UI fecha editor após promessa, mas SELECT e UPDATE contacts finais usam o mesmo can_edit_contact (SQL corroborado). Não se demonstrou usuário com leitura permitida e UPDATE negado estruturalmente. Conflito concorrente/deleção pode produzir zero rows e permanece risco genérico, não novo bypass ou finding material.'),
 dict(id='D-AUTH-30', paths=['src/hooks/system/useNotifications.ts','src/components/notifications/NotificationItem.tsx','src/components/notifications/NotificationsPopover.tsx'],
      status='CROSS_REVIEW_NO_DUPLICATE_COUNT', reason='Revisão independente de R2-PLAT-002 do root: unreadCount é estado separado, markAsRead pode decrementar item já lido e UPDATE realtime pode intercalar. Root mantém o achado e probes PLAT-P02/P03. Outros limites visuais: query cap100 sem count, DELETE realtime sem ajuste e popover sem erro/loading. Não duplicados aqui; não se afirma perda de registro.'),
 dict(id='D-AUTH-31', paths=['src/hooks/system/useNotificationSettings.ts','src/components/notifications/NotificationSettingsPanel.tsx'],
      status='CROSS_REVIEW_NO_DUPLICATE_COUNT', reason='Revisão independente de R2-PLAT-004 do root: resetSettings atualiza cache e aguarda upsert sem ler error; handleReset não aguarda e anuncia reset imediato. Root mantém achado e probe PLAT-P05. updateSettings principal checa error e informa falha com invalidação, controle positivo verificado.'),
 dict(id='D-AUTH-32', paths=['src/hooks/system/useNotificationSettings.ts','src/components/notifications/NotificationTypeCards.tsx','src/hooks/realtime/useRealtimeNotifications.ts','src/hooks/sla/useSLANotifications.ts','src/hooks/inbox/useSentimentAlerts.ts'],
      status='CROSS_REVIEW_NO_DUPLICATE_COUNT', reason='Revisão independente de R2-PLAT-003 do root: newMessageSound/mentionSound/slaBreachSound não entram no SELECT/mapDbToSettings/dbUpdates e voltam true ao refetch. useRealtimeNotifications25–63 também ignora newMessageSound; controles SLA53–56 e menção74–79 são efetivos em memória. Root mantém achado/probe PLAT-P04 e ampliou consumo com a evidência enviada. Candidato AUTH038 de notificações não foi publicado nem contado; ID038 é do mapa.'),
 dict(id='D-AUTH-33', paths=['src/components/admin/PlaybooksManager.tsx'],
      status='GENERIC_ERROR_LIMIT_NO_DETERMINISTIC_AUTH_MISMATCH', reason='DELETE não lê error antes do toast; UPDATE não confirma count. Porém policies finais de playbooks permitem escrita a admin/supervisor, conforme SQL20260409014536:130–133 corroborado pelo agente database. Não há no-op determinístico de supervisor provado. Falha eventual de transporte permanece observação, sem novo achado material.'),
 dict(id='D-AUTH-34', paths=['src/components/auth/HeroBenefits.tsx','src/components/auth/SocialProof.tsx'],
      status='EXTERNAL_CLAIMS_NOT_VERIFIED', reason='Métricas comerciais, selo SOC2/LGPD e disponibilidade99.9% são textos estáticos. A fonte local não comprova essas declarações; ausência de evidência local não prova que certificação/disponibilidade sejam falsas. Não contado como defeito de segurança nem validação externa concluída.'),
 dict(id='D-AUTH-35', paths=['src/components/contacts/ContactsTable.tsx','src/components/contacts/ContactMapView.tsx','src/components/contacts/ContactKpiCard.tsx'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='Tabela ordena o array da página localmente; percentuais por região usam a maior região como100%, não o total; geometria de Sparkline merece QA visual com muitas amostras. São limites de apresentação/escopo, sem mutação ou inferência de vazamento. O mapa com conjuntos sobrepostos é tratado materialmente em AUTH038.'),
 dict(id='D-AUTH-36', paths=['src/components/admin/AIUsageDashboard.tsx','src/hooks/analytics/useAIUsageDashboard.ts'],
      status='STATIC_PRESENTATION_LIMIT', reason='Gráfico de áreas enumera somente seis chaves fixas FUNCTION_COLORS, embora o resumo retorne chaves dinâmicas; pizza/lista de funções suportam nomes novos. Erros das queries não são expostos pelo hook ao painel. Agregação de totais e paginação real são controles positivos. Recorte visual separado dos contratos temporais/custo AUTH040/041.'),
 dict(id='D-AUTH-37', paths=['src/components/gamification/GamificationProvider.tsx','src/components/gamification/DemoAchievements.tsx','src/providers/AppProviders.tsx','src/App.tsx'],
      status='UNMOUNTED_PROVIDER_AND_ACTIVE_NOOP_DEMO', reason='Nenhuma montagem produtiva de GamificationProvider foi localizada por símbolo/import e leitura da árvore. DemoAchievements é montado no widget e recebe NOOP_CONTEXT: seus botões de teste não persistem/mostram conquistas apesar do texto Suas conquistas são salvas automaticamente. Fila/processQueue que captura currentAchievement antigo, toast de prêmio após erro e grant repetido são limitações do provider dormente, não bugs operacionais contados. AchievementsPanel acessado por Ver Conquistas consulta dados reais de forma independente. Não se propõe ligar provider sem revisar autorização/recompensas.'),
 dict(id='D-AUTH-38', paths=['src/components/gamification/miniGamesData.ts','src/components/gamification/MiniGameDialogs.tsx','src/components/gamification/TrainingMiniGames.tsx'],
      status='LOW_IMPACT_STATIC_OBSERVATION', reason='Response Match é um dos quatro cartões oferecidos, mas só há diálogos de Speed Typing/Quiz/Emoji: clicar nele apenas muda selectedGame/isPlaying sem jogo. Emoji considera resposta vazia correta porque qualquer answer inclui string vazia. Quiz conserva setTimeout sem cancelamento no fechamento. Recordes são locais sem namespace de usuário/validação JSON. Observações do catálogo/avaliação/estado; não se afirma crédito real de XP, pois AUTH043 mostra ausência de consumidor. Lifecycle reproduzido de outro jogo é AUTH044.'),
 dict(id='D-AUTH-39', paths=['src/hooks/gamification/useLeaderboard.ts','src/components/gamification/AchievementsPanel.tsx','src/components/gamification/AchievementsStats.tsx','src/hooks/gamification/useAgentGamification.ts'],
      status='PRIOR_CONFIRMED_AND_PRESENTATION_LIMITS', reason='DASH-REALTIME-001 já descreve resposta antiga por período no useLeaderboard; leitura integral confirma ausência de cancelamento/geração e previousRank igual ao atual (DASH-METRICS-001), sem nova contagem. Período p_period é efetivo, contrariando documento antigo. AchievementsPanel filtra/conta apenas últimos20 da query e não expõe error; limite visual sem novo finding material.'),
 dict(id='D-AUTH-40', paths=['src/components/ai/AutoTicketClassifier.tsx','supabase/functions/ai-classify-tickets/index.ts','src/components/ai/ChurnPredictionDashboard.tsx'],
      status='PRIOR_FINDING_REFINED_NO_NEW_COUNT', reason='IA-METRICS-001 já exige que erro não produza sucesso local. Leitura completa amplia evidência: AutoTicketClassifier122–135 descarta data do invoke, cujo endpoint só devolve results/summary sem persistir, e depois relê tags pelas regras inline. Mesmo erro de invoke gera toast.success Classificação local aplicada. Switch autoClassify43/158 só altera estado decorativo. Backend existe e protege autenticação/RLS; não se alega função inexistente. Churn também mantém fallback/scores locais já descritos. Coordenado com infra, sem novo ID independente.'),
 dict(id='D-AUTH-41', paths=['src/components/ai/ticketClassification.ts','src/components/ai/churnRisk.ts','src/components/ai/AutoTicketClassifier.tsx','src/components/ai/ChurnPredictionDashboard.tsx'],
      status='HELPER_NOT_CONSUMED_BY_PRODUCTION_COMPONENT', reason='Helpers groupTagsIntoTickets e computeChurnRisk não são importados pelos componentes, que conservam cópias inline. Validação de linhas malformadas e clamp de datas futuras presentes nos helpers não demonstram proteção na UI. Busca de símbolos de produção não encontrou consumidor; testes do helper não foram executados nem usados como prova da integração. Evidência compartilhada com infra.'),
]
for item in extra_rejected:
    supp['rejected_or_pending'] = [r for r in supp['rejected_or_pending'] if r['id'] != item['id']]
    supp['rejected_or_pending'].append(item)
supp['new_findings'].sort(key=lambda r:r['id'])
supp['last_extended_at'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
(OUT / 'second-pass.json').write_text(json.dumps(supp,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'findings_in_supplement':len(supp['new_findings']),
                  'reviewed_files':len(supp['reviewed_files']),
                  'last_extended_at':supp['last_extended_at']}))
