"""Documentation-only roster close; no shell, Docker, SQL or product test executed."""
from pathlib import Path
from collections import Counter
import hashlib,json,subprocess
from merge_finite_batch import merge_batch
R=Path('/workspace/scratch/f8f9b9cbce53/reaudit'); S=R/'source'; O=R/'reports/infra'
H='da307ba5626dce892f0b37cb6762463f55d14a96'
notes={
'calls-telefonia-contract.test.sh':('Docker com nome PID e cleanup restrito; readiness estável; set-Eeuo/ON_ERROR_STOP1. Schema/roles/policies mínimos, três migrations, asserts de escopo/raw RLS, filtro/paginação/KPI, dono, NULL profile/owner, notas, chamadas WhatsApp, grants e reaplicação.', 'expect_failure41–51 aceita qualquer erro, sem SQLSTATE; positivos e queries de estado reduzem o risco, mas não provam a causa de toda recusa. Reaplicação365 cobre a migration base, não as duas correções posteriores. Não certifica a cadeia completa nem o overload mais recente.'),
'mapa-f1-address-contract.test.sh':('Container PID network none, mktemp/cleanup, readiness por log+SELECT, ON_ERROR_STOP1. Aplica migrations reais, mede assinatura/campo de endereço, trigger só em mudança, cleared e ausência de PII no audit.', 'ACL98–103 consulta grantees diretos e verifica anon ausente/authenticated presente, sem testar PUBLIC apesar do título; PUBLIC permitiria anon por herança. A função is_admin_or_supervisor da fixture sempre true: não prova escopo de agente.'),
'multiplix-delivery-leases.test.sh':('Container PID, retry apenas bootstrap, ON_ERROR_STOP1, migrations reais em fixture explícita auth/vault/cron/net. Verifica tokens distintos, reclaim e conflito do token antigo, cancel/timeout, ordem de três blocos, heartbeat, dead letters, optout, risco de conexão e atribuição linked/inferred com janela/contato.', 'Claims339–349 são sequenciais: não simulam corrida simultânea. F57.3 declara item pending, mas item1 foi reclaimado365 e permanece sending com lease90; recusa392 não isola pausa. O timeout claim422 ocorre após dispatch cancelled, também não isola só outcome_unknown. F59.4–5 mede gravação da supressão e lista imutável, não um envio real. Erros tolerados nos captures são em geral confrontados com valores/exceções específicos. positivos de outro item e token velho preservados.'),
'talkx-campaign-worker-lease.test.sh':('Docker PID/cleanup, bootstrap até duas respostas estáveis, ON_ERROR_STOP1; expect_error exige nonzero+needle. ACL has_function_privilege, negativas42501, start idempotente, bloqueio worker direto, claim/renew/release, duas fixtures de fila (47/limite20 e subconjunto2), segredo só avaliado como não nulo.', 'Fixture mínima; leases sequenciais e expiração por UPDATE com escape GUC, sem concorrência real. Sorting313 reordena recipient_id na query externa, portanto não certifica a ordem original do set retornado; conjunto pequeno319 também reordena. Não leu segredo real.'),
'talkx-lifecycle-events.test.sh':('Docker PID e cleanup, retry bootstrap, ON_ERROR_STOP1. Fixture de perfis/campanhas/recipients/events; migration real. Transições reais+persistência de quatro eventos/ator/motivo, cancel5, no-complete cancelada, resumed_auto e complete com resumo.', 'Cabeçalho promete soltar leases, mas recipients são criados com leases NULL e não há assertion das colunas de lease. Conclusão usa UPDATE sent direto e contadores0, coerentes com resumo esperado; não prova contadores de envio reais.'),
'talkx-overview-stats.test.sh':('Docker PID/cleanup, fail-fast SQL. Registro CASES_SEEN exige todos13 casos após asserts. Fixture de políticas e roles, migration real+replay, eliminação de overload, has_function_privilege, números atuais/anteriores, dias/zero-fill/somas, dedup, filtros, canal, previous null e sessão agente/admin.', 'Escopo é schema/policies mínimos declarados, não cadeia completa. Fluxo muda dados só no container; maior parte numérica é como postgres, e o bloco RLS usa SET ROLE real. Não se executou nem confirmou resultado das13 medições nesta auditoria.'),
'talkx-send-budget.test.sh':('Docker PID/cleanup e retrybootstrap; ON_ERROR_STOP1. Cadeia explícita10migrations e schema mínimo. Assert objetos3, orçamento minuto/dia, soma Multiplix/TalkX por conexão, pace, clampfast e exceção específica de max_per_minute.', 'GUC role/sub sem SET ROLE nos casos: testa gates internos, não grants/RLS de um usuário autenticado. Orçamento lido sequencialmente, sem reserva concorrente; não substitui provas de envio. jqget definido181 não usado e sem ON_ERROR_STOP, sem consumidor ativo no script.'),
'talkx-suppress-phone-axis.test.sh':('Docker RANDOM+PID/cleanupvalidado, readiness por segundo marker, ON_ERROR_STOP1. Migrations phoneaxis+X029 reaplicadas, overload antigo eliminado, conflitos phone/contato retornam NULL, nova supressão UUID, has_function_privilege dos3roles.', 'Captures com ||true confrontam saída vazia/UUID; erros típicos não passam como sucesso vazio. Casos comportamentais usam postgres+GUC; ACL verificada separadamente. Não mede disputa simultânea nem serviço real.'),
'talkx-transition-overload-postgrest.test.sh':('Docker PG+PostgREST+rede com nomes PID e cleanup restrito. SQL failfast, guard exige status+mensagem; reproduz2overloads, erro CHECK, aplica3migrations, NOTIFY schema, prepara JWT sintético HMAC e invoca testeDeno com falha propagada.', 'Se executado, faz pull de imagem/redeDocker e inicia serviços: não é script read-only. /tmp/talkx-transition-deno.log é caminho compartilhado, não isolado por PID; nota de robustez, sem corrida executada. ChamadaDeno/HTTP não ocorreu. Comentário de estado vigente é histórico do conjunto aplicado, não atestado de deployment.'),
'talkx-v16-time-series.test.sh':('Docker RANDOM/cleanupvalidado, readiness, fixture mínima; função antiga transcrita para RED3, migration real para GREEN5 e campo médio não nulo. Assert diferencia somas3/5 e mede resultado real se rodado.', 'psql helper9 usa ON_ERROR_STOP0; não prova aplicação integral sem erro, mesmo com ||fail na migration109. RED é cópia local da função antiga, não checkout histórico. Verifica presença de avg_reply_secs, não seu valor. Nenhuma execução.'),
'talkx-v21-launch-flags.test.sh':('Docker RANDOM/cleanupvalidado e readiness; fixture mínima, RED semcoluna, migration real, quatrocolunas/defaults, launched_by/at, erro específico adminonly e flags persistidas.', 'ON_ERROR_STOP0linha10 permite prosseguir em erros de arquivo. Fixture cria service_role/authenticated39–40, mas omite anon citado nos REVOKEs da migration114–115/369–370; assertions comportamentais não medem ACL. Captura save_out permissiva152 é seguida de checkreal true:true153–154, controle positivo preservado.'),
'team-reaction-membership.test.sh':('Docker PID e mktemp/cleanup, failfast ON_ERROR_STOP1, helpers de negativos com status+needle. SQL anterior transcrito com duas policies permissivas e NOTNULL; migration real aplicada entre A/B, reseed, ataques diretos/RPC, visibilidade vítima, bloqueios, controles legítimos e contagem/predicado final da policy.', 'Prova é sobre fixture de policies e migration escolhida; não inclui todas as RLS de tabelas vizinhas nem estado atual de plataforma. SQL de seed contém DELETE globais apenas no container recém-criado pelo script; não é cleanup de produto nem INF006. Não foi executado.')}
roster=json.loads((O/'shell-review-roster.json').read_text()); rows=[];inv=[]
for f in roster['files']:
 p=S/f['path'];data=p.read_bytes();n=len(data.decode().splitlines())
 assert hashlib.sha256(data).hexdigest()==f['source_sha256'] and n==f['line_end']
 assert subprocess.check_output(['git','hash-object',str(p)],text=True).strip()==f['git_blob_sha']
 control,limit=notes[p.name]
 rows.append(dict(**f,review_status='READ_COMPLETE',reviewed_ranges=[[1,n]],controls=control,limitations=limit,adjudication='NO_NEW_INF_ID; concrete proof limits retained for TC-011 where applicable',execution='NOT_EXECUTED'))
 inv.append(dict(path=f['path'],sha256=f['source_sha256'],git_blob_sha=f['git_blob_sha'],bytes=len(data),lines=n,baseline_sha=H,reviewed_ranges=[[1,n]],review_level='semantic',full_file_read=True,primary_delegated=True,layer='shell_contract_tests',review_basis=control+' Limites: '+limit))
assert len(rows)==12 and sum(x['line_end'] for x in rows)==3554
support=[('supabase/migrations/20261001231230_f32b_multiplix_item_queue_rpcs.sql',[[92,166]],'Claim exige dispatchsending e pending/failed_transient ou sendingcomleasevencido; revalida interpretação do teste de pausa.'),('supabase/migrations/20260930640000_talkx_v21_launch_flags.sql',[[369,381]],'REVOKE referencia anon ausente na fixture V21; leitura dirigida de apoio, não nova cobertura integral da migration.')]
for path,spans,note in support:
 p=S/path;b=p.read_bytes();n=len(b.decode().splitlines());spans=[[a,min(z,n)]for a,z in spans]
 inv.append(dict(path=path,sha256=hashlib.sha256(b).hexdigest(),bytes=len(b),lines=n,baseline_sha=H,reviewed_ranges=spans,review_level='targeted',full_file_read=False,primary_delegated=False,layer='shell_contract_support',review_basis=note))
def dump(name,d): (O/name).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
dump('shell-review.json',dict(schema_version=1,baseline_sha=H,status='COMPLETED',files=rows,completed_files=12,completed_lines=3554,product_suites_executed=0,probes_executed=0,new_findings=0))
dump('shell-review-findings.json',dict(schema_version=1,baseline_sha=H,findings=[],shared_family='TC-011',notes='Limites concretos das assertions registrados por arquivo; preservados todos os43INF, sem contar runtime não executado.'))
dump('shell-review-coverage.json',dict(schema_version=1,baseline_sha=H,state='COMPLETED',primary_files=12,primary_lines=3554,primary_full_file_read=12,primary_remaining=0,counts=dict(total=len(inv),**Counter(x['review_level']for x in inv)),inventory=inv))
md='# Leitura integral dos12 scripts shell de contrato\n\nLote fechado:12 arquivos/3.554 linhas no HEAD `'+H+'`. Zero scripts, SQL, Docker, Deno, serviço, suíte ou probe executado. A leitura incluiu setup, SQL embutido, migrations selecionadas, branches/assertions, status de erro e cleanup. Credenciais nos fixtures são sintéticas; nenhum segredo real foi lido ou publicado.\n\nAs operações mutáveis desses scripts, quando executados, apontam para containers criados pelo próprio runner. Não foram confundidas com execução somente leitura nem com o cleanup de reações do E2E produtivo. Os controles positivos reais são preservados, assim como o limite de schema mínimo. Nenhum novo ID INF foi criado. Limites concretos de oráculo (pausa com item já inelegível, ACL PUBLIC não medido, psql permissivo/role ausente) foram encaminhados à família TC-011.\n\n'
for row in rows: md+='## '+row['path']+'\n\nFaixa1–'+str(row['line_end'])+'; SHA256 `'+row['source_sha256']+'`; blob `'+row['git_blob_sha']+'`.\n\n'+row['controls']+'\n\n'+row['limitations']+'\n\n'
md=md.replace('dos12','dos 12').replace('fechado:12','fechado: 12').replace('Faixa1','Faixa 1')
(O/'shell-review.md').write_text(md);(O/'shell-review-report.md').write_text(md)
print(json.dumps(merge_batch('shell-review','shell_review','scripts shell de contrato',43,artifacts=['shell-review.json','shell-review-roster.json','shell-review.md','finalize_shell_review.py']),ensure_ascii=False,indent=2))
