"""Close the finite telemetry/error review; all writes are audit documentation."""
from pathlib import Path
from collections import Counter
import json
from merge_finite_batch import BASE, OUT, SRC, HEAD, digest, dump, merge_batch

def ev(path,a,b,reason):
    assert 1<=a<=b<=len((SRC/path).read_text().splitlines())
    return dict(path=path,line_start=a,line_end=b,sha256=digest(SRC/path),baseline_sha=HEAD,origin='source',reason=reason)

findings=[
    dict(id='R2-INF-040',title='Falha de leitura da telemetria aparece como sistema com bom desempenho',severity='P2',classification='novo',baseline_sha=HEAD,area_extension='finite_telemetry_error_batch',
        description='A queryFn lança o error do SDK, mas AdminTelemetriaPage não consome error/isError/status. Sem dados prévios, o default rows=[] chega à tabela quando a primeira consulta terminou em falha. TelemetryTable usa somente isLoading e rows.length e exibe uma mensagem explícita de bom desempenho, enquanto os cards mostram zero erros e média 0ms.',
        consumer_chain=['NavigationService autoriza view telemetry para admin','ViewRouter verifica acesso e monta AdminTelemetriaPage','useQuery recebe rejeição da leitura query_telemetry','Página descarta estado de erro e passa rows=[]/isLoading=false','Tabela anuncia bom desempenho'],
        preconditions=['Usuário com acesso à view de telemetria.', 'Consulta inicial falha depois das tentativas configuradas e não há dados de sucesso no cache dessa chave; não há configuração externa que faça throwOnError.'],
        effect='Uma indisponibilidade ou erro de autorização/consulta é apresentada como ausência de consultas lentas e bom desempenho, justamente quando a tela deveria comunicar que não conseguiu medir. O achado não depende de números reais do banco nem afirma exposição a usuários sem acesso.',
        evidence=[ev('src/pages/AdminTelemetriaPage.tsx',37,59,'Estado de erro omitido; queryFn lança SDK error'),ev('src/pages/AdminTelemetriaPage.tsx',70,98,'Cards calculados do array vazio'),ev('src/pages/AdminTelemetriaPage.tsx',145,148,'Contador e tabela sem estado de erro'),ev('src/pages/admin-telemetria/TelemetryTable.tsx',13,28,'Sem dados vira mensagem explícita de bom desempenho'),ev('src/lib/queryClient.ts',9,25,'Configura retries, mas não eleva todo erro de query à ErrorBoundary'),ev('src/pages/ViewRouter.tsx',81,87,'View telemetry é consumidor ativo'),ev('src/pages/ViewRouter.tsx',129,151,'Gate de acesso presente antes da montagem'),ev('src/services/navigation.service.ts',142,155,'Telemetria restrita por papel no mapa de navegação')],
        acceptance=['Consumir e apresentar falha da query, separada de carregamento, sucesso vazio e sucesso com registros.','Não derivar saúde do sistema de ausência de dados por falha; se houver dados de cache, sinalizar atualização falha/defasagem.','Verificar falha inicial, sucesso vazio, sucesso com alertas e falha de refetch; manter os gates de acesso e o erro já validado pelo cleanup.'],
        affected_tasks=[],probe_ids=['INF-TE-P01'],related_previous_findings=['R2-INF-026'],novelty_basis='Outro consumidor e mecanismo: este SDK error é lançado corretamente e o erro é perdido na apresentação de useQuery, não nas checagens de saúde de Diagnostics.',proof_type='STATIC_AND_BOUNDED_SYNTHETIC_OFFLINE',
        limitations=['Nenhuma query de produto, biblioteca React/TanStack, browser ou retry real executado.','Probe usa o queryFn real com SDK sintético e fornece o estado de erro documentado à fronteira do hook; testa as decisões de página/tabela reais.','A classe de severidade e o limite de 500 registros não foram convertidos em defeitos adicionais.'],
        external_references=[dict(url='https://tanstack.com/query/latest/docs/framework/react/guides/queries',retrieved_on='2026-10-04',source_kind='primary_documentation',supports='Query com falha é distinguida por isError/status e error; a ausência de dados não equivale a sucesso vazio.')]),
    dict(id='R2-INF-041',title='ErrorBoundary ignora fallback nulo usado para retirar overlays com falha',severity='P2',classification='novo',baseline_sha=HEAD,area_extension='finite_telemetry_error_batch',
        description='O contrato de Props aceita fallback ReactNode, mas render verifica seu valor por truthiness. Quando App fornece fallback={null} para os providers diferidos, a condição é falsa e o boundary renderiza a tela padrão de erro, com min-h-screen e role=alert. App documenta expressamente que esse fallback deve retirar silenciosamente a camada opcional.',
        consumer_chain=['App mantém AppRoutes fora do boundary de overlays','DeferredProviders/DeferredHooks são filhos de ErrorBoundary fallback=null','Uma falha chega ao estado hasError','render ignora o fallback explícito null e retorna a UI padrão'],
        preconditions=['O boundary de overlays da aplicação captura uma falha e permanece em hasError.', 'O fallback fornecido é null, como no consumidor atual; para chunk load, após a recuperação automática não ser possível ou já ter sido usada.'],
        effect='Uma falha de componente opcional produz um painel de erro com altura mínima de uma viewport e anúncio assertivo em vez de desaparecer. AppRoutes continua fora e montado; não se afirma que o roteamento ou toda a aplicação foi derrubado. A ocupação visual foi confirmada como classe/JSX, não medida em navegador.',
        evidence=[ev('src/components/errors/ErrorBoundary.tsx',8,13,'Fallback é ReactNode opcional'),ev('src/components/errors/ErrorBoundary.tsx',129,142,'if truthy ignora null e cai na UI padrão'),ev('src/App.tsx',15,24,'Contrato de recuperação silenciosa dos overlays'),ev('src/App.tsx',128,143,'Consumidor real fornece null e mantém AppRoutes fora do boundary')],
        acceptance=['Distinguir fallback não fornecido de fallback fornecido como null/false/zero/string vazia; retornar o ReactNode explícito.','Verificar erro com fallback=null, fallback customizado e ausência de fallback, além do caminho sem erro.','Manter os wrappers de sessionStorage, limitação de autoreload e isolamento de AppRoutes; validar em browser que a camada opcional desaparece sem deslocar a aplicação.'],
        affected_tasks=[],probe_ids=['INF-TE-P02'],related_previous_findings=[],novelty_basis='Contrato produtivo específico de fallback nulo; diferente da simples presença de ErrorBoundary em imports ou dos retries de UI genérica.',proof_type='STATIC_AND_BOUNDED_SYNTHETIC_OFFLINE',
        limitations=['Probe chama o método render real isolado, com DEV=false e JSX inerte; não executa componentDidCatch, reportClientError ou reload.','O comentário de main.tsx sobre um wrapper não montado foi tratado pelo root como observação; não compõe este achado.','Os controles de chunk recovery e ocultação de detalhes em produção foram lidos e preservados.'])
]

targets=json.loads((OUT/'telemetry-error-targets.json').read_text())
primary={e['path'] for e in targets['targets']}
notes={
 'src/components/errors/ErrorBoundary.tsx':('Leitura integral: recuperação de chunks exige storage legível e gravável, flag evita loop; retry/home/reload limpam flag com catch. Detalhes DEV condicionados, render fallback truthy é INF-041. Export ErrorFallback não teve consumidor produtivo localizado além de reexport; sem alegação de exposição desse export.',None),
 'src/pages/AdminTelemetriaPage.tsx':('Leitura integral: queryKey inclui filtros, query limitada a 500 mais recentes com erro lançado; apresentação ignora isError (INF-040). Cleanup verifica SDK error. Calendário custom e polling lidos; truncamento e ausência de datas explícitos como limites, não novo defeito automático.',None),
 'src/pages/admin-telemetria/TelemetryStatsCards.tsx':('Leitura integral: quatro cards recebem agregados; não buscam dados. Rótulos e zero/média seguem o pai, sustentando efeito de INF-040 sem ID separado.',None),
 'src/pages/admin-telemetria/TelemetryTable.tsx':('Leitura integral: loading, sucesso vazio e linhas; vazio afirma bom desempenho sem receber erro do pai (INF-040). Colunas/limiares/labels de data e severidade inspecionados.',None),
 'src/pages/admin-telemetria/TelemetryTopOffenders.tsx':('Leitura integral: oculta vazio e exibe até oito grupos recebidos, count/max/média; divisor só ocorre em grupo com linha. Contrato é alertas dos registros carregados, sem query adicional.',None),
 'src/pages/admin-telemetria/telemetryTypes.ts':('Tipos integrais de linha, severidade e período; schema estático não valida dados remotos por si só.',None),
 'src/pages/admin-telemetria/telemetryUtils.tsx':('Leitura integral: formatos, badges e agrupamento top oito por frequência; dias de calendário em São Paulo são decisão explícita para 7d, horas corridas preservadas para 1h/6h/24h.',None),
 'src/components/admin/telemetry/TelemetryCharts.tsx':('Leitura integral de apoio: buckets floor por duração, severidade/contagem/média/máximo e ranking. Usa somente rows filtrado; 500 mais recentes limitam série. Sem chamada ou mutação, sem nova medição fictícia.',None),
 'src/lib/queryClient.ts':('Leitura integral de apoio: singleton, retries de queries e networkMode online; mutations sem retry. Não configura throwOnError global nem converte toda query em suspense.',None),
 'src/pages/admin-telemetria/__tests__/telemetryUtils.periodo.test.ts':('Asserções/fixtures integrais lidas, sem executar: importa helper real; data fixa e Intl São Paulo testam meia-noite, sete dias calendário e horas corridas. Não prova a apresentação de erro da página.',None),
 'infrastructure/preview-egress-proxy/main.go':('Releitura integral para explicitar a faixa antes implícita: HMAC corpo/timestamp/nonce, retenção até expiração da aceitação, mutex/capacidade, limites de body/time/redirect, validação de todas respostas DNS e dial de IP validado preservando SNI/Host. Erros externos genéricos. Nenhum Go/servidor/rede iniciado.',None),
 'infrastructure/preview-egress-proxy/main_test.go':('Releitura integral de assertions: IP/URL privados, autenticação/replay com clock à frente, pin de dial/SNI/Host e rejeição de DNS privado antes do dial. TLS insecure é fixture do httptest; teste inicia serviço local se executado, mas não foi executado nesta auditoria.',None),
 'src/App.tsx':('Apoio dirigido: contrato e montagem de overlays opcionais com fallback null, AppRoutes irmão fora do boundary. Nenhum handler global foi executado.',[[1,45],[118,150]]),
 'src/pages/ViewRouter.tsx':('Apoio dirigido: mapeamento ativo telemetry e gate de acesso antes de ViewComponent. Erro de useQuery não é automaticamente exceção de render.',[[75,90],[125,152]]),
 'src/services/navigation.service.ts':('Apoio dirigido: item telemetry com ADMIN_ONLY; não se presume acesso universal.',[[142,155]]),
 'docs/evidencias/plano-volume-50/mut-plano-volume.py':('Trechos de apoio da extensão INF-019 revisada integralmente pelo root: baseline, rodar e mutações com finally/SHA. Nonzero indiscriminado continua inadequado para provar assertion alvo; não se executou o script.',[[95,154]]),
}
inventory=[]
for path,(note,ranges) in sorted(notes.items()):
    p=SRC/path;n=len(p.read_text().splitlines());ranges=ranges or [[1,n]]
    assert all(1<=a<=b<=n for a,b in ranges)
    full=ranges==[[1,n]]
    inventory.append(dict(path=path,sha256=digest(p),bytes=p.stat().st_size,lines=n,baseline_sha=HEAD,reviewed_ranges=ranges,review_level='semantic' if full else 'targeted',full_file_read=full,primary_delegated=path in primary,layer='telemetry_error_delegated' if path in primary else 'telemetry_error_support',review_basis=note))
assert len(primary)==7 and targets['primary_lines']==685
assert all(next(e for e in inventory if e['path']==p)['full_file_read'] for p in primary)
remaining=['Nenhum browser, SDK real, banco, TLS, Go runtime ou serviço iniciado.','Probes usam fonte real e fronteiras inertes; não substituem React/TanStack nem a execução de seus ciclos.','O limite de 500 registros representa uma amostra recente, não certifica métricas de todo o banco; não foi promovido a um novo mecanismo sem promessa mais específica.','A leitura integral dos sete arquivos fecha apenas o lote delegado; o roster final de testes permanece em andamento.']
history=['Primeira execução interrompida por guarda do harness: import.meta.env.DEV aparece também em comentário, tornando a contagem textual 2. A substituição foi restringida à expressão JSX exata; os dois casos passaram depois. Nenhuma falha do harness virou achado.']
coverage=dict(schema_version=1,area='infra_telemetry_error',baseline_sha=HEAD,state='COMPLETED',primary_files=7,primary_lines=685,primary_full_file_read=7,primary_remaining=0,counts={'total':len(inventory),**dict(Counter(e['review_level'] for e in inventory))},inventory=inventory,remaining_gaps=remaining,harness_history=history)
dump('telemetry-error-coverage.json',coverage)
dump('telemetry-error-findings.json',dict(schema_version=1,area='infra_telemetry_error',baseline_sha=HEAD,findings=findings,previous_findings_compared=104,remaining_gaps=remaining,changed_existing_finding='INF-019 recebeu extensão de locus histórico, sem novo ID; builder da segunda passagem também foi atualizado.'))
report=['# Revisão de telemetria e tratamento de erros','',f'Sete arquivos primários lidos integralmente: 685 linhas. HighContrastToggle já foi fechado como apoio no lote anterior. Há {len(inventory)} caminhos com apoio: {coverage["counts"]["semantic"]} integrais e {coverage["counts"]["targeted"]} dirigidos. Fonte `{HEAD}`; nenhuma alteração de produto.','','## Resultado e prova delimitada','','Dois achados, dois casos offline. INF-TE-P01 verifica a falha lançada pela query real com SDK sintético e a apresentação real da página/tabela para um estado documentado de erro. INF-TE-P02 chama somente render do ErrorBoundary. Nenhum caso executa React, TanStack, browser, rede ou reload.','',history[0]]
for f in findings:
    report+=['',f'## {f["id"]} — {f["title"]}','',f['description'],'','**Precondições:** '+' '.join(f['preconditions']),'','**Efeito:** '+f['effect'],'','**Evidência:**','',*[f'- `{e["path"]}:{e["line_start"]}–{e["line_end"]}` — {e["reason"]}. SHA256 `{e["sha256"]}`.' for e in f['evidence']],'','**Aceite:**','',*[f'- {s}' for s in f['acceptance']],'','**Limites:** '+' '.join(f['limitations'])]
    if f.get('external_references'): report+=['','Contrato primário: [TanStack Query — Queries](https://tanstack.com/query/latest/docs/framework/react/guides/queries), consultado em 04/10/2026. Estados de erro e sucesso são distintos; a documentação não é captura de execução do produto.']
report+=['','## Controles e adjudicação','','Cleanup da telemetria já verifica SDK error. Os períodos de sete dias são deliberadamente de calendário em São Paulo e os testes importam o helper real. O gate de acesso à view foi preservado. Chunk recovery possui wrappers de storage e limitação de recarga; ErrorFallback exportado não foi promovido sem consumidor. Nenhuma tarefa DONE_VERIFIED foi reaberta por semelhança temática.','','INF-019 recebeu um locus histórico adicional por revisão compartilhada com root. O script de volume tem baseline, alvo literal, finally e SHA; o achado preserva esses controles e limita a extensão à contagem de qualquer nonzero como PEGA. Não é um terceiro achado deste lote.','','## Cobertura por arquivo','','| Arquivo | Nível | Faixas | Avaliação |','|---|---|---|---|',*[f'| `{e["path"]}` | {e["review_level"]} | '+', '.join(f'{a}–{b}' for a,b in e['reviewed_ranges'])+' | '+e['review_basis'].replace('|','/')+' |' for e in inventory],'','## Lacunas','','',*[f'- {s}' for s in remaining],'']
(OUT/'telemetry-error-report.md').write_text('\n'.join(report))
probes=json.loads((OUT/'telemetry-error-probes.json').read_text());assert probes['case_count']==2
result=merge_batch('telemetry-error','telemetry_error_review','telemetria e tratamento de erros',39,artifacts=['telemetry-error-probes.json','telemetry-error-probe-pins.json','probe-telemetry-error.mjs','finalize_telemetry_error_review.py','extend_inf019.py','append_second_pass.py','findings-second-pass.json'])
print(json.dumps({k:result[k] for k in ['finding_total','finding_counts','coverage_counts','evidence_refs','source_evidence_refs']},ensure_ascii=False))
