# Loaded by build_report.py after the preserved pass4 findings.
assert len(F) == 53

add('Editar resposta rápida reutiliza o formulário anterior e pode gravá-lo em outro template', 'P2',
 'QuickReplyDialog inicializa formData uma única vez a partir de editingTemplate. O comentário de sincronização não tem efeito correspondente. QuickRepliesManager mantém o componente montado sem key quando fecha ou troca o template, e handleSubmit usa o ID atual com os campos antigos.',
 'Configurações → Mensagens, com QuickRepliesManager não compacto. Na mesma montagem, abrir Editar, preencher ou salvar A, fechar e abrir B; a primeira edição após montagem também começa com o formulário vazio inicial.',
 'A edição não apresenta os dados do registro escolhido. Ao salvar B, o callback de update recebe o ID de B com o título/conteúdo ainda pertencentes ao formulário de A, permitindo sobrescrever B.',
 [('src/components/inbox/quick-replies/QuickReplyDialog.tsx',20,35,'Estado inicial não acompanha editingTemplate; submit combina ID atual e formData retido.'),
  ('src/components/inbox/QuickRepliesManager.tsx',29,31,'O primeiro render fornece editingTemplate=null.'),
  ('src/components/inbox/QuickRepliesManager.tsx',60,60,'Fechamento limpa apenas o alvo/abertura no pai.'),
  ('src/components/inbox/QuickRepliesManager.tsx',111,124,'Editar muda prop; diálogo permanece montado sem key.'),
  ('src/components/inbox/quick-replies/QuickReplyCardList.tsx',98,102,'Ação Editar alcançável por template.'),
  ('src/components/settings/SettingsView.tsx',138,144,'Consumidor ativo monta o modo não compacto.')],
 ['Abrir edição deve carregar os campos do template escolhido; abrir criação deve usar um formulário novo.',
  'Definir explicitamente como conservar um rascunho sem transferi-lo para outro ID.',
  'Teste do consumidor deve abrir A e B sucessivamente sem remontar o manager e verificar o payload enviado a cada ID.'],
 ['quick_reply_dialog_stale_target'], ['2.32'],
 limits='Probe executa estado/handler reais com fronteira de update local. Prova o payload destinado a B; não escreve no banco nem mede incidência produtiva. Remontar o diálogo com B como controle inicial carrega os dados corretos.')

add('Filtro de grupos remove o hífen que sua própria expressão exige', 'P2',
 'isGroup remove todos os caracteres não numéricos e depois testa uma expressão que exige um hífen entre dois grupos de dígitos. O predicado fica falso para qualquer entrada, e todas as categorias de grupo dependem dele.',
 'Uma conversa de grupo já está presente no conjunto carregado. O usuário seleciona Todos os Grupos ou uma subcategoria no filtro de tipo; também afeta Chats Individuais.',
 'Todas as opções de grupos retornam uma lista vazia. Chats Individuais inclui as conversas de grupo, porque usa a negação do mesmo predicado.',
 [('src/components/inbox/ContactTypeFilter.tsx',29,30,'Normalização destrói o separador obrigatório da regex.'),
  ('src/components/inbox/ContactTypeFilter.tsx',40,92,'Categorias individuais e de grupo compartilham esse predicado.'),
  ('src/hooks/inbox/useInboxFilters.ts',164,165,'Filtro real da Inbox aplica filterByContactType.'),
  ('src/components/inbox/InboxFilters.tsx',174,193,'As opções estão disponíveis na interface ativa.')],
 ['Classificar grupo por identidade/tipo canônico compatível com a representação dos contatos.',
  'Cobrir grupo com hífen, contato individual e todas as subcategorias sem depender de fixture apenas numérica.',
  'O contador/lista resultante deve corresponder ao tipo selecionado.'],
 ['group_filter_removes_required_hyphen'], ['2.6'],
 limits='O predicado é determinístico, e a fixture explicita um grupo previamente carregado. Não afirma quantos grupos existem ou estão acessíveis no serviço atual.')

add('Contador Em atendimento e badge de responsável comparam auth ID com profile ID', 'P2',
 'StatusChips compara assigned_to com user.id da sessão. VirtualizedRealtimeList passa a mesma identidade Auth para decidir se o badge representa outro atendente. O contrato de contacts.assigned_to referencia profiles.id, enquanto o filtro real de atendimento usa profileId.',
 'Usuário tem profiles.id diferente do auth user.id e há uma conversa atribuída ao seu perfil. O schema permite identidades distintas; não se pressupõe que todas as contas produtivas já satisfaçam essa condição.',
 'O chip Em atendimento pode mostrar zero enquanto o filtro correspondente contém a conversa. A lista também pode exibir o próprio responsável como se fosse outro atendente.',
 [('src/components/inbox/conversation-list/StatusChips.tsx',24,46,'Contagem de atendimento usa user.id.'),
  ('src/components/inbox/VirtualizedRealtimeList.tsx',107,109,'Identidade obtida da sessão Auth.'),
  ('src/components/inbox/VirtualizedRealtimeList.tsx',243,243,'user.id segue como currentUserId ao item.'),
  ('src/components/inbox/VirtualizedRealtimeList.tsx',317,318,'Condição compara assigned_to com identidade Auth.'),
  ('src/components/inbox/VirtualizedRealtimeList.tsx',420,435,'Badge usa a condição de responsável diferente.'),
  ('src/hooks/inbox/useInboxFilters.ts',88,91,'Filtro correto compara com profileId.'),
  ('src/integrations/supabase/types.ts',2308,2312,'FK gerada: assigned_to referencia profiles.id.'),
  ('src/integrations/supabase/types.ts',6054,6077,'Profile possui campos id e user_id separados.'),
  ('src/components/inbox/__tests__/StatusChips.test.tsx',6,8,'Teste fixa Auth user-1.'),
  ('src/components/inbox/__tests__/StatusChips.test.tsx',25,29,'Fixture atribui ao mesmo ID, ocultando a diferença.')],
 ['Usar profile.id de maneira uniforme nos filtros, contadores e comparação do responsável.',
  'Definir o estado enquanto o perfil ainda não foi resolvido.',
  'Testar uma sessão com auth ID e profile ID diferentes e conferir chip, resultado e badge em conjunto.'],
 ['status_chip_uses_auth_id_for_profile_fk'], ['2.1','2.6'],
 relation='Nova falha no consumidor Inbox. O achado anterior DASH-SQL-REGRESSION-001 já incluía assigned_to=auth.uid em dashboard_contact_counts; é outro corpo e outro consumidor. AUTH011 trata visibilidade de metadados de colegas, não esta comparação de identidade.',
 limits='Probe executa a contagem e a condição de badge reais. Não cria perfis nem consulta IDs produtivos. Igualar as identidades na fixture é um controle positivo e explica por que o teste atual passa.')

add('VoiceChangerPicker mantém ou inicia captura depois de fechar ou desmontar', 'P1',
 'O componente tem cleanup que para tracks, porém só o chama no fechamento explícito do Popover. Não há efeito de desmontagem. startRecording também aguarda getUserMedia sem verificar geração, montagem ou abertura antes de armazenar o stream e iniciar MediaRecorder.',
 'Transformador de voz do Composer: iniciar gravação e trocar de contato, desmontando ChatPanel por key; ou fechar o popover enquanto a permissão está pendente e concedê-la depois.',
 'A captura pode permanecer ativa com a interface desmontada ou começar após o popover já estar fechado. O usuário perde o controle visível para interromper esse stream.',
 [('src/components/inbox/VoiceChangerPicker.tsx',1,1,'Imports React não incluem efeito de cleanup.'),
  ('src/components/inbox/VoiceChangerPicker.tsx',62,97,'cleanup existe, mas await getUserMedia não tem validação de ciclo antes de iniciar captura.'),
  ('src/components/inbox/VoiceChangerPicker.tsx',185,190,'Limpeza é ligada ao fechamento explícito, não ao unmount.'),
  ('src/components/inbox/chat/ChatInputToolbars.tsx',59,61,'Transformador montado no Composer.'),
  ('src/components/inbox/RealtimeInboxView.tsx',298,301,'Troca de contato remonta ChatPanel por key.')],
 ['Garantir liberação idempotente de recorder e tracks na desmontagem e no descarte explícito.',
  'Depois de getUserMedia resolver, validar geração/montagem/abertura e interromper imediatamente qualquer stream já obsoleto.',
  'Cobrir falha do construtor, fechamento com permissão pendente e troca de contato durante gravação, sem deixar handlers antigos ressuscitarem estado.'],
 ['voice_picker_unmount_keeps_stream','voice_picker_permission_resolves_after_close'], ['4.1','3.4'],
 relation='Outro gravador e outra causa em relação a R2-INB-008: AudioRecorder tem cleanup com closure antiga; VoiceChangerPicker não registra cleanup de desmontagem e não invalida a permissão pendente. Não reconta VOL-01 do AudioContext de reprodução.',
 limits='Tracks e MediaRecorder são sintéticos; não houve permissão ou microfone físico. A prova usa o corpo real sem efeito e o callback literal onOpenChange. A remoção do componente por key não chama automaticamente o callback de fechamento do popover.')

add('Áudio gerado e voz transformada descartam a prévia antes do resultado do envio', 'P2',
 'TextToAudioButton e VoiceChangerPicker tipam seus callbacks de envio como void e não aguardam o consumidor assíncrono. Ambos limpam blob/URL, fecham e anunciam sucesso enquanto o envio no pai ainda está pendente.',
 'Usuário gera áudio a partir de texto ou transforma uma gravação e clica Enviar. O upload/conversão já terminou, mas o envio posterior demora e falha, incluindo rejeição antes do enqueue.',
 'A interface confirma envio e remove a prévia que permitiria tentar novamente. O erro posterior do pai contradiz o sucesso, sem recuperar o áudio gerado.',
 [('src/components/inbox/TextToAudioButton.tsx',14,17,'Callback onAudioReady é void.'),
  ('src/components/inbox/TextToAudioButton.tsx',29,41,'cleanup descarta prévia/blob.'),
  ('src/components/inbox/TextToAudioButton.tsx',109,115,'Callback não aguardado, fechamento e sucesso imediatos.'),
  ('src/components/inbox/VoiceChangerPicker.tsx',42,44,'Callback onSendAudio é void.'),
  ('src/components/inbox/VoiceChangerPicker.tsx',162,184,'Após upload, envia sem await, limpa e mostra sucesso.'),
  ('src/components/inbox/chat/ChatInputToolbars.tsx',59,79,'Os produtores usam callbacks do Composer.'),
  ('src/components/inbox/ChatPanel.tsx',288,297,'Ponte fornece handlers assíncronos.'),
  ('src/components/inbox/chat/useChatPanelHandlers.ts',270,275,'Pai aguarda envio e captura falha só depois.'),
  ('src/components/inbox/useChatMediaSending.ts',119,133,'Voz transformada chega a envio assíncrono que também pode falhar.')],
 ['Propagar um resultado assíncrono explícito até cada produtor de áudio.',
  'Conservar blob e prévia durante pendência e falha; limpar somente após aceite ou descarte solicitado.',
  'Reusar identidade/objeto quando o resultado do envio for incerto e impedir cliques duplicados enquanto aguarda.'],
 ['generated_tts_send_before_outbound','transformed_voice_send_before_outbound'], ['3.4','4.5'],
 relation='Novos produtores com contrato void. R2-INB-010 cobre agendamento; R2-INB-022 cobre o gravador comum. A aceitação necessária é semelhante, mas os callbacks que precisam de correção são distintos.',
 limits='Fronteiras de conversão, fetch, Storage e transporte foram simuladas. A perda demonstrada é a prévia de áudio; o texto original pode continuar no editor. Não se afirma que todo erro posterior deixa objeto órfão ou que o provedor recebeu uma mensagem.')

add('Miniatura com assinatura em lote não consegue renovar a URL que falha', 'P2',
 'Quando item.signedUrl existe, ThumbImage e FileDetailContent chamam useResolvedStorageUrl com string vazia e preferem sempre item.signedUrl no src. O refresh ligado ao erro não recebe o locator original e retorna vazio. A consulta fornece assinaturas de uma hora, sem renovação automática por expiresAt no consumidor.',
 'Aba Arquivos carregou imagem privada com assinatura em lote. A assinatura expira ou é invalidada antes de outra atualização da consulta, e o navegador precisa buscar a imagem novamente ou a carrega pela primeira vez depois disso.',
 'O handler de recuperação não solicita nova assinatura e mantém a URL defeituosa; a imagem cai no estado indisponível apesar de o locator e a permissão de leitura poderem continuar válidos.',
 [('src/components/inbox/tabs/FileThumb.tsx',87,115,'Assinatura em lote desativa source do resolver; onError chama seu refresh.'),
  ('src/components/inbox/tabs/FileDetailPanel.tsx',25,30,'Detalhes repetem source vazio e preferência por signedUrl.'),
  ('src/components/inbox/tabs/FileDetailPanel.tsx',49,51,'Falha chama refresh sem locator.'),
  ('src/hooks/storage/useResolvedStorageUrl.ts',47,59,'Sem referência reconhecida, refresh retorna source sem assinar.'),
  ('src/hooks/chat/useContactMedia.ts',66,66,'TTL das assinaturas em lote é uma hora.'),
  ('src/hooks/chat/useContactMedia.ts',154,188,'signInBatch cria as URLs de leitura.'),
  ('src/hooks/chat/useContactMedia.ts',263,285,'Itens recebem signedUrl/expiresAt; staleTime não é intervalo de renovação.'),
  ('src/components/inbox/tabs/__tests__/FileThumb.test.tsx',15,17,'Mock do resolver ignora argumento.'),
  ('src/components/inbox/tabs/__tests__/FileThumb.test.tsx',69,99,'Teste de refresh bem-sucedido não fornece signedUrl em lote.')],
 ['Manter o locator original disponível para renovar assinatura em lote ou individualmente.',
  'Uma URL renovada deve substituir o src antigo e limpar estado de erro.',
  'Testar item com signedUrl presente, expiração/falha, renovação bem-sucedida e ausência de loop de refresh.'],
 ['batch_signed_thumbnail_cannot_refresh'], ['2.26','2.36'],
 relation='Contrato distinto de R2-INB-033, que trata refresh tardio de A após mudar a referência para B. Este defeito aparece em um único item que já recebeu signedUrl.',
 limits='Erro de imagem é injetado; nenhum HTTP de Storage foi executado. Não se afirma que imagem já completamente carregada desaparece no instante em que a URL expira. O controle sem assinatura em lote renova corretamente com o resolver real.')

add('Detalhes de arquivo conservam o erro da imagem anterior ao selecionar outro item', 'P2',
 'FileDetailContent mantém hasError em estado local inicializado uma vez e o define como true em onError, sem reset por item/src. FilesTab troca selected dentro da mesma instância de detalhes sem key por arquivo.',
 'Na mesma conversa e painel de detalhes, a imagem A falha e o usuário seleciona B, cuja URL é válida. O caminho largo com detalhes inline conserva essa montagem.',
 'B fica com placeholder de erro em vez da imagem válida. Fechar/remontar o painel recupera a apresentação, mas selecionar outro arquivo não limpa o erro.',
 [('src/components/inbox/tabs/FileDetailPanel.tsx',25,30,'Estado hasError não depende da identidade do item.'),
  ('src/components/inbox/tabs/FileDetailPanel.tsx',42,56,'O ramo de imagem depende de hasError e onError o torna true.'),
  ('src/components/inbox/tabs/FilesTab.tsx',285,287,'Seleção de detalhes troca selected.'),
  ('src/components/inbox/tabs/FilesTab.tsx',305,314,'Instância inline recebe novo item sem key por arquivo.')],
 ['Associar erro à identidade/URL que falhou ou reiniciar estado quando item/src mudar.',
  'A renovação bem-sucedida também deve permitir renderizar novamente.',
  'Testar A com erro seguido de B válido no mesmo painel sem desmontagem.'],
 ['file_detail_error_persists_into_next_item'], ['2.26','2.36'],
 relation='Separado da assinatura vazia de R2-INB-059 e do refresh concorrente de R2-INB-033: a causa é estado de erro do componente preservado entre arquivos.',
 limits='Probe usa estado, resolver e onError reais sem DOM/HTTP. A fixture usa URLs públicas para isolar a falha de estado de qualquer assinatura. Não atravessa o key de contato do painel principal.')

add('Falha ao carregar scoring habilita salvar defaults sobre dados existentes', 'P2',
 'LeadRiskScorePanel inicia scores em zero e origem/consentimento vazios. O SELECT ignora error e define loaded=true mesmo sem dados. O botão Salvar continua disponível, e save envia todos os campos, inclusive os defaults que nunca foram carregados.',
 'O mesmo contato já possui scores/consentimento. A leitura falha transitoriamente; o usuário altera apenas um campo e salva quando a escrita já pode ser aceita. A troca de contato é protegida pelo key da view e não é a precondição do achado.',
 'Campos existentes não carregados podem ser substituídos por zero ou null ao salvar uma edição parcial. A interface não distingue estado real vazio de falha de carregamento.',
 [('src/components/inbox/LeadRiskScorePanel.tsx',27,46,'Defaults seguidos de loaded=true sem tratar error da consulta.'),
  ('src/components/inbox/LeadRiskScorePanel.tsx',54,67,'Save envia todos os campos do estado.'),
  ('src/components/inbox/LeadRiskScorePanel.tsx',138,146,'Botão de salvar depende de saving, não de leitura válida.'),
  ('src/components/inbox/contact-details/ContactAccordionSections.tsx',108,114,'Painel ativo no accordion de scoring.'),
  ('src/components/inbox/RealtimeInboxView.tsx',338,344,'Key por contato afasta hipótese genérica de estado A→B.')],
 ['Tratar falha de leitura como erro recuperável e impedir salvar valores que não foram carregados.',
  'Enviar somente campos efetivamente editados quando o contrato admitir patch parcial.',
  'Testar SELECT com error seguido de escrita autorizada no mesmo contato, preservando os valores não alterados.'],
 ['lead_score_failed_load_writes_defaults'], ['2.5'],
 limits='Banco é um modelo local com falha de leitura e escrita posterior autorizada. Não demonstra dados reais nem faz afirmação jurídica sobre consentimento. A hipótese de mistura entre contatos foi rejeitada após conferir a montagem por key.')

add('Controle Recentes do administrador de figurinhas não muda a coleção', 'P3',
 'StickerManager altera showRecent e o fornece ao indicador visual de StickerCategoryBar, mas filteredStickers depende somente de favorito, categoria e busca. A consulta/ordem e a grade não consomem showRecent.',
 'Configurações → Mídia → administrador de figurinhas compartilhadas. Usuário alterna o controle Recentes.',
 'O controle muda de estado visual, porém a mesma coleção e ordem continuam na grade; não há efeito de filtro ou ordenação por recência.',
 [('src/components/inbox/stickers/StickerManager.tsx',28,31,'Estado showRecent inicializado.'),
  ('src/components/inbox/stickers/StickerManager.tsx',81,87,'Filtro ignora showRecent.'),
  ('src/components/inbox/stickers/StickerManager.tsx',149,157,'Toggle afeta apenas estado passado à barra.'),
  ('src/components/inbox/stickers/StickerManager.tsx',176,184,'Grade recebe somente filteredStickers.'),
  ('src/components/inbox/stickers/StickerCategoryBar.tsx',46,58,'Controle Recentes indica seleção.'),
  ('src/components/settings/SettingsView.tsx',188,194,'Consumidor administrativo alcançável.')],
 ['Definir recência com campo apropriado e ligar o controle ao filtro/ordem correspondentes.',
  'Alternar Recentes/Todas deve produzir resultado coerente e contagem clara.',
  'Cobrir o administrador separadamente do picker principal, que tem lógica própria.'],
 ['sticker_manager_recent_toggle_no_effect'], ['3.11'],
 relation='Nova ação sem efeito no administrador. R2-INB-051 trata janela máxima do catálogo; a coleção deste cenário pode ser pequena e inteiramente carregada.',
 limits='A fixture substitui a consulta e executa o estado/filter reais. Não se afirma que StickerPicker principal tenha a mesma falha nem se impõe recência por uso sem decisão de produto.')

add('Card de resposta rápida anuncia cópia sem escrever no clipboard', 'P2',
 'O clique principal do card chama handleSelect, que incrementa uso, invoca onSelect opcional e mostra Resposta copiada. Em Configurações o manager não recebe onSelect, e esse handler não escreve no clipboard. O botão específico Copiar usa outro handler.',
 'Configurações → Mensagens → clicar no corpo de uma resposta rápida, em vez do ícone dedicado Copiar.',
 'A UI anuncia cópia, mas o clipboard conserva o conteúdo anterior. Colar em seguida não produz a resposta escolhida.',
 [('src/components/inbox/QuickRepliesManager.tsx',33,42,'handleSelect não acessa clipboard; handleCopy é uma rota separada.'),
  ('src/components/inbox/QuickRepliesManager.tsx',111,113,'Manager liga o clique principal a handleSelect.'),
  ('src/components/inbox/quick-replies/QuickReplyCardList.tsx',69,77,'Corpo do card executa onSelect.'),
  ('src/components/inbox/quick-replies/QuickReplyCardList.tsx',95,97,'Ícone específico usa onCopy e para propagação.'),
  ('src/components/settings/SettingsView.tsx',138,144,'Configurações não fornece onSelect ao manager.')],
 ['Fazer o clique cumprir a ação comunicada e confirmar a escrita no clipboard antes de anunciar sucesso.',
  'Separar feedback de inserção no Composer e de cópia em Configurações conforme o consumidor.',
  'Cobrir ausência de onSelect, falha de clipboard e distinção entre corpo do card e ícone.'],
 ['quick_reply_card_reports_copy_without_clipboard'], ['2.32'],
 limits='Clipboard é um array local; nenhum dado real foi copiado. O controle do ícone prova que ele solicita writeText, não que toda implementação/permissão do clipboard sempre aceitará a cópia.')

assert len(F) == 63

add('Ações de alertas de sentimento não oferecem navegação para a conversa', 'P2',
 'O toast local de useSentimentAlerts oferece Ver conversa, mas seu onClick apenas registra contactId em log. O toast global de useRealtimeSentimentAlerts oferece Ver detalhes e tenta clicar em [value="ai"], sem navegar ou usar contact_id quando o elemento não existe.',
 'Variante local: análise válida em AIConversationAssistant recebe alerted=true e notifyCaller não falso, vence o dedupe e mostra o toast. Variante global: alerta realtime chega enquanto a aplicação está em uma tela sem elemento [value="ai"], como o recorte de Inbox fora do Dashboard; contato alertado pode ser diferente do selecionado.',
 'O clique não abre nem foca a conversa alertada. No caminho local só produz log; no global sem alvo DOM retorna sem ação ou feedback. A existência de uma aba dinâmica ai no Dashboard não fornece um destino de conversa às outras telas.',
 [('src/hooks/inbox/useSentimentAlerts.ts',55,71,'Toast local ativo tem onClick limitado a log.debug.'),
  ('src/components/inbox/AIConversationAssistant.tsx',172,183,'Análise válida chama o hook de alerta.'),
  ('src/components/inbox/chat/ChatToolPanels.tsx',28,35,'Assistant é montado pela ferramenta Visão no chat.'),
  ('src/hooks/inbox/useRealtimeSentimentAlerts.ts',50,69,'Ação global usa apenas querySelector/click e não contact_id.'),
  ('src/hooks/inbox/useRealtimeSentimentAlerts.ts',93,115,'Assinatura realtime autenticada entrega o alerta.'),
  ('src/components/notifications/RealtimeSentimentAlertProvider.tsx',4,10,'Provider executa o hook global.'),
  ('src/App.tsx',52,64,'Provider é overlay independente da tela.'),
  ('src/App.tsx',123,143,'DeferredProviders permanece fora da seleção de AppRoutes.'),
  ('src/pages/ViewRouter.tsx',44,58,'Inbox, Dashboard e Sentimento são views distintas.'),
  ('src/pages/ViewRouter.tsx',141,155,'Só a view selecionada é montada.'),
  ('src/components/dashboard/DashboardView.tsx',48,62,'A aba ai existe dinamicamente no Dashboard, com escopo de papel.'),
  ('src/components/dashboard/overview/DashboardTabs.tsx',25,31,'TabsTrigger recebe value dinâmico; não foi alegada ausência universal do produtor.')],
 ['Conectar as ações ao contrato de navegação/seleção de contato e a um destino de detalhe acessível para o papel atual.',
  'Definir feedback quando o contato/detalhe não puder ser acessado, sem depender da presença incidental de um elemento DOM.',
  'Cobrir alerta recebido fora do Dashboard, outro contato selecionado, caminho local e navegação negada por permissão.'],
 ['sentiment_actions_without_conversation_navigation'], ['5.4','20.11'],
 relation='Nova ação de alerta não coberta pelos IDs de métricas/estado saudável de Infra, conforme conferência com o revisor. TRA-011 e AUTH038 permanecem separados. Nenhum achado é criado para alegar ausência universal da aba ai.',
 limits='Probe usa hooks/callbacks reais e DOM mínimo com caso sem alvo e controle com alvo clicável. Não renderiza Radix, não prova qual atributo DOM concreto ele expõe e não declara que o botão do Dashboard sempre falha. Serviços de análise/alertas são simulados.')

assert len(F) == 64

# Additional evidence without changing or recounting previous findings.
PASS5_NOTES = [
 {'id':'PASS5-HANDOFF-VARIANT','kind':'evidência complementar de família existente','related_finding_ids':['R2-INB-009'],
  'assessment':'Adicionar participante → RealtimeCollaboration → HandoffDialog ignora error do UPDATE no pai; a promessa resolve e o diálogo anuncia transferência. A família R2-INB-009 e todos os 53 achados do checkpoint pass4 ficam literalmente preservados, sem novo ID para esta variante.',
  'evidence':[ev('src/components/inbox/contact-details/ContactActionButtons.tsx',173,179,'Popover Adicionar participante monta a colaboração.'),ev('src/components/inbox/RealtimeCollaboration.tsx',18,31,'Handoff ignora error de update e da nota opcional.'),ev('src/components/inbox/collaboration/HandoffDialog.tsx',35,48,'Diálogo aceita promessa resolvida e confirma sucesso.')],
  'offline_probe_ids':['collaboration_handoff_error_variant'],
  'acceptance':'Propagar falha/zero efeito da transferência e da nota conforme contrato; não fechar nem anunciar sucesso antes do resultado aceito.',
  'limits':'Probe usa comentário vazio e nenhuma operação de Auth/banco real. Não afirma atomicidade ou permissões vivas.'},
 {'id':'PASS5-WHISPER-REACHABILITY','kind':'contrato condicional e limite de integração','related_finding_ids':[],
  'assessment':'Se WhisperMode for montado com as props da condição de ChatPanel, falta targetAgentId e sendWhisper retorna sem INSERT. Contudo, o estado inicial whisper é false e os comandos/ações lidos não estabelecem abertura desse estado. Não há finding confirmado de jornada ativa, nem declaração de dead code.',
  'evidence':[ev('src/components/inbox/ChatPanel.tsx',72,98,'Estado inicial e controlador dos diálogos.'),ev('src/components/inbox/ChatPanel.tsx',282,286,'Montagem condicional não fornece targetAgentId.'),ev('src/components/inbox/WhisperMode.tsx',90,114,'Handler exige alvo antes de persistir.')],
  'offline_probe_ids':['whisper_conditional_consumer_omits_target'],
  'acceptance':'Antes de homologar Sussurro, definir rota de abertura e seleção do alvo; só então provar a jornada e sua autorização.',
  'limits':'A prova monta o componente artificialmente. Não substitui evidência de uma ação do produto que o torne acessível.'},
 {'id':'PASS5-TAGS-EXISTING','kind':'extensão de cobertura anterior','related_finding_ids':['TRA-011'],
  'assessment':'useInboxFilterTags continua sem paginação, como já documentado em TRA-011. A leitura integral também observou que error é ignorado e data ausente vira lista vazia de sucesso; InboxFilters só apresenta a seção quando tags.length>0. Não criado novo ID.',
  'evidence':[ev('src/hooks/inbox/useInboxFilterTags.ts',6,16,'Consulta única, distinct em memória e resultado de error não examinado.'),ev('src/components/inbox/InboxFilters.tsx',74,79,'Consumidor usa apenas data.'),ev('src/components/inbox/InboxFilters.tsx',225,229,'Seção depende de resultado não vazio.')],
  'offline_probe_ids':[],
  'acceptance':'A revisão de TRA-011 deve considerar paginação/agregado e erro recuperável de consulta sem apagar o último catálogo válido.',
  'limits':'Não consulta cardinalidade/RLS produtiva; a observação de erro é estática.'},
 {'id':'PASS5-VOICE-LOG-LIMIT','kind':'limite de telemetria','related_finding_ids':[],
  'assessment':'logVoiceCommand é explicitamente fire-and-forget e não lê response.ok do POST; erro HTTP pode perder log sem feedback. Na ausência de contrato durável de entrega não se promove uma nova falha de ação nem se exige bloquear o usuário.',
  'evidence':[ev('src/hooks/voice/logVoiceCommand.ts',15,46,'Fluxo assíncrono não bloqueante e fetch sem inspeção do status.'),ev('src/hooks/communication/useVoiceAgent.ts',110,119,'Consumidor registra sucesso antes de entregar ação ao callback.')],
  'offline_probe_ids':[],
  'acceptance':'Se logs forem requisito durável, definir sinalização/retenção/retry e separar resultado de interpretação do resultado da ação; conservar UI não bloqueante.',
  'limits':'Nenhum log ou credencial real foi enviado; não se afirma taxa de perda no serviço.'},
]
(OUT/'pass5-notes.json').write_text(json.dumps({'source_sha':SHA,'counted_as_new_findings':False,'notes':PASS5_NOTES},ensure_ascii=False,indent=2)+'\n')
