-- GAP-01 auditoria 02/09/2026: idx_messages_whatsapp_connection_id tinha 0 scans
-- desde reset. ux_messages_dedup(whatsapp_connection_id, external_id, sender)
-- ja cobre wc_id como col[0] - o planner usa para FK constraint check via
-- leading column scan. DROP elimina 96 kB de write overhead gratuito em
-- cada INSERT de mensagem.
--
-- Evidencia:
--   idx_scan = 0 (pg_stat_user_indexes, pos-reset em 20260901)
--   ux_messages_dedup leading column = whatsapp_connection_id
--   Seq Scan preferred for wc_id-only queries (2 connections ~5700 msgs cada)
--
-- IF EXISTS: idempotente (convencao do repo; indice pode ter sido removido
-- manualmente em ambientes de dev/staging antes desta migration rodar).
DROP INDEX IF EXISTS public.idx_messages_whatsapp_connection_id;
