-- ledger-only/comment-only: migration aplicada via MCP em 2026-09-27 sem arquivo versionado no momento.
-- ledger_name: security_revoke_anon_9rpcs_wa_tag_search_path
-- SQL histórico preservado no ledger (sem código executável recuperável sem acesso ao banco).
-- Ver migration-evidence.json para esta versão.
